Sources/Net/NetService.swift

Library periodically crashes on clients.append and clients.remove in NetService:

Fixed crash in NetService

---

Sources/Media/AVMixerRecorder.swift
Sources/Media/VideoIOComponent.swift

Fix Issues #138, now record video will have full FPS
Fix record video quality when add effects

Fix Issues #138, now record video will have full FPS

---

Platforms/iOS/ScreenCaptureSession.swift

Added new init function which receives UIView instead of UIApplication.
Made shared:UIApplication optional
In case if UIView is passed, size = view.bounds.size, otherwise it is same as it was.

Modify ScreenCaptureSession to capture passed UIView

---

Sources/RTMP/RTMPConnection.swift

this fixes https://github.com/shogo4405/lf.swift/issues/233

fix red5 compat

---

Sources/RTMP/RTMPTSocket.swift

unlocks video encoder from rtmpt socket
https://github.com/shogo4405/lf.swift/issues/233

red5+rtmpt unlock video encoder

---

Sources/RTMP/RTMPTSocket.swift

unlock encoder lock after copying to outputBuffer
AND outputQueue.sync of `idle()` requests
(this helps red5 survive) :)

sync idle requests

---

README.md

Added docs regarding activation of AVAudioSession

---

Examples/iOS/LiveViewController.swift
Sources/Media/AVMixerRecorder.swift
Sources/Net/NetStream.swift

allow this happen in the application level.

dont export by default in the library.

---

Sources/RTMP/RTMPConnection.swift
soe/src/Main.mxml

Hi, I found some typos in the library!

Fixed some typos :)

---

Sources/Codec/AACEncoder.swift
Sources/Codec/H264Encoder.swift
Sources/Media/AVMixer.swift

Mark methods designated for KVC as @objc

---

Sources/Media/AVMixerRecorder.swift

Mark extension as @objc

---

Sources/Media/VideoIOComponent.swift

Call `attachStream` on main queue

---

Sources/Codec/AACEncoder.swift

Hi I believe this fixes random crashes in AudioConverterFillComplexBuffer mentioned in issues some time back. 
I believe the logic of AACEncoder.encodeSampleBuffer is not perfect. See for example the last paragraph here: https://developer.apple.com/library/content/qa/qa1317/_index.html - calling AudioConverterFillComplexBuffer can not assume that all data will be produced in a single shot.
Calling AudioConverterFillComplexBuffer does not ensure all data from converted to be consumed so we need to call it in a loop to ensure that as much as possible data was consumed from the encoder.
I'm not 100% sure about return codes, this is but a good and working attempt to fix it. You should check if the pulling loot will always terminate (always gets status <= 0)
As a side-effect this fixes #320 …

fixed crash in AudioConverterFillComplexBuffer

---

Sources/Net/NetStream.swift

Fixes issue #429 
Basically, #429 problem is caused by using `dispatch_sync` (`lockQueue.sync`) from the concerned queue, which can cause deadlocks, which crash the app running.
This PR aims to check which is current queue to use `lockQueue.sync` only if the code's not already running on the queue.
Half the code is @clmntcrl's, huge thanks to him for his help!

Avoid dispatch_sync deadlocks (#429)

---

Sources/Media/VideoIOComponent.swift

For better performance, If needed use CIImage.

CVPixelBuffer Pass-Through

---

Examples/iOS/AppDelegate.swift
Sources/Codec/AACEncoder.swift
Sources/ISO/PacketizedElementaryStream.swift
Sources/ISO/TSWriter.swift
Sources/RTMP/RTMPMuxer.swift

Don't create a CMSampleBuffer.

---

Sources/ISO/MP4Reader.swift

this will parse multiple child boxes in MP4VisualSampleEntryBox 
sample file here http://kote.videogorillas.com/vmir/GOPR9152.LRV

parse multiple boxes in MP4VisualSampleEntryBox

---

Sources/Codec/AACEncoder.swift
Sources/HTTP/HTTPStream.swift
Sources/ISO/H264+AVC.swift
Sources/ISO/PacketizedElementaryStream.swift
Sources/ISO/TSWriter.swift
Sources/RTMP/RTMPMuxer.swift

1. Fix not compatible to thread-safe (might be fixed #450 )
1. Divide TSWriter -> TSWriter and TSFileWriter

Refactor TSWriter

---

README.md

I think it will be TLS - Transport Layer Security. Not TSL.

Typo fix TLS - Transport Layer Security

---

Sources/Media/AVMixer.swift
Sources/Media/VideoIOComponent.swift

Reverts shogo4405/HaishinKit.swift#512

Revert "Add the ability to disable the iPhone camera stabilization"

---

HaishinKit.podspec
README.md

Hello!
You forgot to update version and documentation.
Also, please update cocoapods with the new podspec.
Thank you!

BUMP 0.10.7

---

HaishinKit.podspec

fix GL deprecation warning

---

Sources/Net/NetSocket.swift
Sources/RTMP/RTMPConnection.swift
Sources/RTMP/RTMPSocket.swift
Sources/RTMP/RTMPTSocket.swift

1. Fixed issue #555 
1. Add qualityOfService property for NetSocket, RTMPConnection.

Immediately close for reconnect.

---

Sources/RTMP/RTMPStream.swift

Addresses issue described here: #577

Send bitrate in kbps for setDataFrame

---

Sources/Codec/H264Encoder.swift

MaxKeyFrameIntervalDuration needs invalidateSession

---

Sources/RTMP/RTMPMessage.swift

If the composition time is non-zero, timestamp value will be negative and casting to UInt32 will fail.
I fixed that pts and dts are calculated correctly when the composition time is non-zero (when the video has a b-frame)

Fix negative timestamp value when the composition time is not zero

---

Sources/RTMP/AMF0Serializer.swift
Sources/RTMP/ASClass.swift

By default they are deserialized into a new type `ASTypedObject`, with a type name, and an object data.
My custom model
```swift
// avchat3.Room
struct Room : Decodable {
let name: String
let welcomeMessage: String
let description: String
}
```
Registering type during initialization
```swift
ASTypedObject.register(type: Room.self, named: "avchat3.Room")
```

Support for decoding custom typed objects

---

Platforms/iOS/NetStream+Extension.swift
Platforms/iOS/ScreenCaptureSession.swift
Platforms/iOS/VideoIOComponent+Extension.swift
Sources/Codec/H264Encoder.swift
Sources/Media/VideoIOComponent.swift
Sources/RTMP/RTMPStream.swift

added protocol to allow stream of CVPixelBuffer to be 'screen capture'
added a few helpful logs

support custom capture

---

Sources/Net/NetSocket.swift

Refactoring NetSocket.swift

---

Examples/iOS/LiveViewController.swift
Examples/iOS/Preference.swift
Platforms/iOS/GLHKView.swift
README.md
Sources/Media/AVMixer.swift
Sources/Media/VideoIOComponent.swift

https://developer.apple.com/documentation/avfoundation/avcaptureconnection/1389172-isvideomirrored

Support isVideoMirrored property.

---

Sources/Util/Setting.swift
Tests/Util/SettingTests.swift

```swift
let size: CGSize = .zero
rtmpStream.videoSettings = [
.width: size.width
.height: size.height
]
```

Fix number conversion from CGFloat to Int(UInt).

---

Sources/RTMP/RTMPConnection.swift

Fix 'objectEncoding' value in connect message

---

Examples/iOS/LiveViewController.swift
Sources/Codec/AudioConverter.swift
Sources/Codec/H264Encoder.swift
Sources/RTMP/RTMPStream.swift

It seems like the unit of kbps for bitrate is incorrect.
Although it did not say it's based on kbps, I think kbps should be the unit here :)
ref: https://en.wikipedia.org/wiki/Bit_rate

fix: change the unit of kbps from 1024 to 1000

---

Examples/iOS/Preference.swift
Sources/Net/NetSocket.swift

#606 Might be fixed crash on NetStream.

Might be fixed crash on NetStream and decrease memory usages.

---

Examples/iOS/Main.storyboard
Examples/iOS/PlaybackContainerViewController.swift
Examples/iOS/PlaybackViewController.swift
HaishinKit.xcodeproj/project.pbxproj
Platforms/iOS/HKPictureInPicureController.swift
Platforms/iOS/HKPictureInPicureControllerImpl.swift

Add PictureInPicture feature

---

Sources/Net/NetSocket.swift
Sources/RTMP/RTMPNWSocket.swift

* DispatchWorkItem を一度キャンセルすると同じ物を使いまわすことができなくなるため、タイムアウトの処理が行われない場合がある
* DispatchWorkItem をスケジュールする直前で生成するよう修正

タイムアウト時の処理が行われない場合がある問題を修正

---

README.md

@shogo4405 small update to Stream sponsorship URL

Updated Stream sponsorship URL

---

Package.swift

Update minimum version in Swift Package to tvOS 10.2

---

Sources/Codec/AudioCodec.swift

Fixed compile error Xcode13

---

Examples/iOSSwiftUI/ContentView.swift
Sources/Net/NetSocket.CircularBuffer.swift

fixed Error in SwiftUI Canvas

---

Sources/Codec/AudioCodec.swift

Workaround is here. I'm under tesing.
https://github.com/shogo4405/HaishinKit.swift/issues/1016

fixed Can't publish Audio with iOS16b1

---

Gemfile.lock
Platforms/iOS/DeviceUtil+Extenstion.swift
fastlane/Fastfile
fastlane/README.md

add spm build check

---

Sources/Codec/VideoCodec.swift

Fix name to reflect new filename

Update VideoCodec.swift Queue Name

---

Platforms/iOS/HKView.swift
Platforms/macOS/HKView-macOS.swift
Sources/Media/MTHKView.swift
Sources/Media/PiPHkView.swift
Sources/Media/ScalingMode.swift
Sources/RTMP/ASClass.swift

add PiPHKView macOS.

---

Sources/Media/AVRecorder.swift

fix #869 Local record audio desynchronization on camera switch

---

Cartfile
Examples/iOS/AppDelegate.swift
Examples/iOS/Screencast/SampleHandler.swift
HaishinKit.podspec
Package.swift
Sources/Util/Constants.swift

Bump up Logboard to 2.3.0

---

.swiftlint.yml
Examples/iOS/LiveViewController.swift
Examples/iOS/PlaybackViewController.swift
Examples/iOSSwiftUI/Model/ViewModel.swift
Examples/iOSSwiftUI/iOSSwiftUIApp.swift
Examples/macOS/AppDelegate.swift
Examples/macOS/MainViewController.swift
HaishinKit.xcodeproj/project.pbxproj
Platforms/macOS/DisplayLink-macOS.swift
Sources/Codec/VideoCodec.swift
Sources/ISO/ProgramSpecific.swift

- Suppress warnings  SwiftLint

Suppress warnings  SwiftLint

---

.github/workflows/review.yml
HaishinKit.xcodeproj/project.pbxproj
Sources/Codec/AudioCodec.swift
Sources/Codec/VideoCodec.swift
Sources/Extension/CMSampleBuffer+Extension.swift
Sources/Extension/CVPixelBuffer+Extension.swift
Sources/Extension/CVPixelBufferPool+Extension.swift
Sources/Media/AVAudioIOUnit.swift
Sources/Media/AVIOUnit.swift
Sources/Media/AVRecorder.swift
Sources/Media/AVVideoIOUnit.swift
Sources/Net/NetStream.swift
Sources/RTMP/RTMPStream.swift
fastlane/Fastfile

- fixed https://github.com/shogo4405/HaishinKit.swift/issues/955
- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1075
- Removed `stream.audioSettings["muted"]` and `stream.videoSettings["muted"]`
- Use `stream.hasAudio = false/true`, `stream.hasVideo = false/true`.

Add hasAudio, hasVideo options.

---

Platforms/iOS/AVVideoIOUnit+Extension.swift
Sources/FLV/FLVReader.swift
Sources/HTTP/HLSService.swift
Sources/HTTP/HTTPStream.swift
Sources/Media/AVVideoIOUnit.swift
Sources/Net/NetStream.swift
Sources/TS/TSWriter.swift

- Remove cast code that `error to NSError`.

NSError -> Error

---

Examples/iOS/LiveViewController.swift
HaishinKit.xcodeproj/project.pbxproj
Platforms/macOS/AVVideoIOUnit+Extension-macOS.swift
Sources/Extension/CMSampleBuffer+Extension.swift
Sources/Extension/vImage_Buffer+Extension.swift
Sources/Media/AVAudioIOUnit.swift
Sources/Media/AVCaptureIOUnit.swift
Sources/Media/AVMixer.swift
Sources/Media/AVVideoIOUnit.swift
Sources/Media/PiPCaptureSetting.swift
Sources/Net/NetStream.swift

- [Advances in Camera Capture & Photo Segmentation ](https://developer.apple.com/videos/play/wwdc2019/225)
- Support an AVCaptureMultiCamSession.
- netStream.attachPiPCamera(device)

[Technical preview] Initial support an AVCaptureMultiCamSession.

---

Examples/iOS/LiveViewController.swift
HaishinKit.xcodeproj/project.pbxproj
Sources/Media/AVAudioIOUnit.swift
Sources/Media/AVMixer.swift
Sources/Media/AVVideoIOUnit.swift
Sources/Media/MultiCamCaptureSetting.swift
Sources/Net/NetStream.swift

- Support multi camera capture on macOS.

Support multi camera capture on macOS.

---

Examples/iOS/LiveViewController.swift
Examples/iOSSwiftUI/Model/ViewModel.swift
HaishinKit.xcodeproj/project.pbxproj
Platforms/iOS/IOVideoUnit+Extension.swift
Platforms/macOS/IOVideoUnit+Extension-macOS.swift
Sources/Codec/VideoCodec.swift
Sources/Media/IOAudioUnit.swift
Sources/Media/IOCaptureUnit.swift
Sources/Media/IOMixer.swift
Sources/Media/IORecorder.swift
Sources/Media/IOUnit.swift
Sources/Media/IOVideoUnit.swift
Sources/Net/NetStream.swift
Sources/RTMP/RTMPStream.swift
Tests/Util/SettingTests.swift

- Rename AVIOUnit to IOUnit.
- I confused `AVFoundation class` name.

Rename AVIOUnit to IOUnit.

---

Examples/iOS/LiveViewController.swift
Sources/Media/IOMixer.swift

- Support background audio stream for a framework layer.

Support background audio stream for a framework layer.

---

HaishinKit.xcodeproj/project.pbxproj
Sources/Extension/AVCaptureDevice+Extension.swift
Sources/Extension/AVCaptureSession.Preset+Extension.swift
Sources/Media/IOMixer.swift

- [A Boolean value that indicates whether the capture session enables access to the camera while multitasking.](https://developer.apple.com/documentation/avfoundation/avcapturesession/4013227-ismultitaskingcameraaccessenable?changes=_2)

Support isMultitaskingCameraAccessEnabled.

---

Sources/Media/IOMixer.swift

Fix spm compile error 1.4.0

---

Sources/Media/IOMixer.swift
Sources/RTMP/RTMPStream.swift

- Added a delegate method to AVCaptureSession handling.

Add AVCaptureSession delegate methods.

---

HaishinKit.xcodeproj/project.pbxproj
Sources/Extension/CVPixelBuffer+Extension.swift
Sources/Extension/vImage_Buffer+Extension.swift
Sources/Extension/vImage_CGImageFormat+Extension.swift
Sources/Media/ShapeFactory.swift

- Improved performance PiP mode for the MultiCamCaptureSetting.
|Befure|After|
|:-:|:-:|
|<img width="364" alt="スクリーンショット 2023-01-01 23 38 54" src="https://user-images.githubusercontent.com/810189/210174895-aa2ca55d-7dc1-45b5-a615-e31e4882b216.png">|<img width="366" alt="スクリーンショット 2023-01-01 23 37 38" src="https://user-images.githubusercontent.com/810189/210174888-906c857c-9ca6-489e-a109-56ab3c91927d.png">|
- iPadAir 5th + iPadOS16.2

Improved performance PiP mode for the MultiCamCaptureSetting.

---

Sources/RTMP/RTMPStream.swift

Reverts shogo4405/HaishinKit.swift#1106

Revert "Fix: add audio sample rate"

---

HaishinKit.xcodeproj/project.pbxproj
Sources/Extension/CVPixelBuffer+Extension.swift
Sources/Extension/vImage_Buffer+Extension.swift
Sources/Media/IOVideoUnit.swift
Sources/Media/ImageTransform.swift
Sources/Media/MultiCamCaptureSetting.swift
Sources/Media/Shape.swift
Sources/Media/ShapeFactory.swift

- Fixed the camera image comes to the center when split display.

Adjust MultiCamCapture splitView position.

---

Examples/macOS/Base.lproj/Main.storyboard
Examples/macOS/CameraPublishViewController.swift
Examples/macOS/MenuViewController.swift
Examples/macOS/PreferenceViewController.swift
Examples/macOS/SCStreamPublishViewController.swift
HaishinKit.xcodeproj/project.pbxproj
Sources/Net/NetStream.swift

- Initial support ScreenCaptureKit on macOS

Support ScreenCaptureKit on macOS

---

Examples/iOS/LiveViewController.swift
Examples/iOS/PlaybackViewController.swift
Sources/Codec/VideoCodec.swift

- Fix MemoryLeak when playback with main or high profile.

fix MemoryLeak when playback with main or high profile.

---

Examples/iOS/LiveViewController.swift
Sources/Media/IOAudioUnit.swift
Sources/Media/IOCaptureUnit.swift
Sources/Media/IOMixer.swift
Sources/Media/IOVideoUnit.swift

- Fixed https://github.com/shogo4405/HaishinKit.swift/issues/1130
- Hard to understand the race condition.

fixed #1130 Single instance IOVideoUnit and IOAudioUnit.

---

Sources/Codec/AudioCodec.swift
Sources/Media/IOCaptureUnit.swift
Sources/Net/NetStream.swift
Sources/RTMP/RTMPStream.swift

- fixed #1103
- Add audiosamplerate metadata.
```
print(createMetaData())
```
```
["audiosamplerate": 44100.0, "height": 1280, "videodatarate": 160, "audiocodecid": 10, "width": 720, "audiodatarate": 32, "videocodecid": 7, "framerate": 30.0]
```

fixed #1103 Add audiosamplerate.

---

Examples/iOS/LiveViewController.swift
README.md

Added handling sample of Adaptive bitrate streaming. 

Added handling sample of Adaptive bitrate streaming.

---

Examples/iOS/Screencast/SampleHandler.swift
Sources/Media/IOMixer.swift
Sources/Net/NetStream.swift

Change method signature appendSampleBuffer.

---

Sources/MPEG/AVCConfigurationRecord.swift
Sources/MPEG/NALUnit.swift

Suppress warnings CMVideoFormatDescriptionCreateFromH264ParameterSets.

---

Examples/iOS/LiveViewController.swift
Sources/Net/NetStream.swift
Sources/RTMP/RTMPConnection.swift
Sources/RTMP/RTMPStream.swift

- Redesigned delegate classes, because I think that delegate methods has increased.

Redesign RTMPConnecitonDelegate and NetStreamDelegate.

---

Sources/Media/IOMixer.swift

- fix https://github.com/shogo4405/HaishinKit.swift/discussions/1011#discussioncomment-5366740

Support publish with audio in background iOS.

---

Sources/Media/IOMixer.swift

Reverts shogo4405/HaishinKit.swift#1161
Release plan change to 1.4.5 to 1.5.0.

Revert "Support publish with audio in background iOS."

---

Sources/Media/IOMixer.swift

- Supports background audio mode framework level.
- https://github.com/shogo4405/HaishinKit.swift/discussions/1011

Supports background audio mode framework level.

---

Sources/Media/IOAudioUnit.swift
Sources/Media/IORecorder.swift

- Fixed. https://github.com/shogo4405/HaishinKit.swift/issues/1147
- Fixed. https://github.com/shogo4405/HaishinKit.swift/issues/755

fix audio desynchronization on camera switch

---

Cartfile
HaishinKit.podspec
Package.swift
Sources/MPEG/ESSpecificData.swift

- Bump to Logboard up 2.3.1
- Fix can't build carthage macOS target with Xcode14.3.

Bump to Logboard up 2.3.1

---

Sources/Codec/AudioCodecSettings.swift
Sources/Codec/VideoCodecSettings.swift

Default videoSize is out of date.

Change default size. It's 2023!

---

Sources/RTMP/RTMPConnection.swift

- Replace NSStream with the Network.framework in the future.

Switched to using the Network.framework.

---

Sources/Codec/VideoCodec.swift
Sources/Extension/AVCaptureDevice+Extension.swift
Sources/Media/IOCaptureUnit.swift
Sources/Media/IOMixer.swift
Sources/Util/DeviceUtil.swift

fixed #1157 Support 60/fps.

---

Sources/Media/IOMixer.swift

Resume AVAudioSession.

---

HaishinKit.xcodeproj/project.pbxproj
Package.swift
Sources/Extension/AVCaptureSession+Extension.swift
Sources/Extension/CMFormatDescription+Extension.swift
Sources/Media/IOMixer.swift
Sources/Net/NetStream.swift

- Possible to build with Mac Catalyst.
- Not tested yet.

Support MacCatalyst for SPM.

---

Sources/RTMP/RTMPNWSocket.swift

- Fix https://github.com/shogo4405/HaishinKit.swift/issues/1185

RTMPNWSoccket will be gracefully close.

---

Sources/Codec/VideoCodec.swift

- I have corrected the mistake where encoding and decoding were swapped.

Fix dropframe delegate.

---

Sources/Media/IOVideoUnit.swift

 Detach camera device stream#attachCamera(nil)

---

Sources/RTMP/RTMPStream.swift

fixed When I set pause and resume, mute will not work bug

---

HaishinKit.xcodeproj/project.pbxproj
Sources/Media/IOAudioUnit.swift
Sources/Util/CMAudioSampleBufferUtil.swift
Tests/Util/CMAudioSampleBufferUtilTests.swift

Fix Rare crash of makeSampleBuffer

---

Sources/Media/IOMixer.swift

- The timing for camera recovery will become faster.
```
2023-15-07 11:00:14.295 [Info] [com.haishinkit.HaishinKit] [IOMixer.swift:434] willEnterForegroundNotification(_:) > 
2023-15-07 11:00:14.591 [Info] [com.haishinkit.HaishinKit] [IOMixer.swift:439] didBecomeActive(_:) > 
```

Improved camera restoration

---

Sources/Media/IOAudioUnit.swift

- fixed #1234
- I think it has likely improved on my end as well #1208.

Reviewed the process for filling the gap.

---

Sources/Codec/AudioCodec.swift
Sources/Codec/AudioCodecRingBuffer.swift
Sources/Extension/CMFormatDescription+Extension.swift

- Fixed https://github.com/shogo4405/HaishinKit.swift/issues/1240

Support ReplayKit audioApp.

---

Sources/Net/NetStream.swift

fixed Version 1.5.4 Cannot find 'UIApplication' in scope

---

Examples/iOS/LiveViewController.swift
HaishinKit.xcodeproj/project.pbxproj
Platforms/iOS/DeviceUtil+Extenstion.swift
Sources/Media/IOAudioMonitor.swift
Sources/Media/IOAudioMonitorRingBuffer.swift
Sources/Media/IOAudioUnit.swift
Sources/Net/NetStream.swift
Tests/Codec/AudioCodecBufferTests.swift
Tests/Codec/AudioCodecTests.swift
Tests/Media/IOAudioMonitorRingBufferTests.swift
Tests/SinWaveUtil.swift

For verification purposes, I have implemented an audio loopback playback feature to check what kind of audio is being captured in reality.

Audio loopback feature.

---

Sources/RTMP/RTMPStream.swift

- Support videocodecid to hevc.
- refs https://github.com/veovera/enhanced-rtmp/issues/8
as expected)

set videocodecid to hevc for enhanced-rtmp

---

Examples/iOS/PlaybackViewController.swift
Sources/Media/IOMixer.swift
Sources/Net/NetStream.swift

invoke sessionInterruptionEnded.

---

Sources/Codec/AudioCodec.swift

- fixed Can't play back aac.
- It was a bug in issue #1234. 

fixed Can't play back aac.

---

Sources/Media/IOAudioMonitor.swift

fixed https://github.com/shogo4405/HaishinKit.swift/issues/1263
**Reproduce Step**
```
stream.loopback = true
```
1. Run [Example app(UIKIt)]
1. Preference 
1. Open Window -> Close Window
1. Repeat the above operation.

fixed Garbage collection crash in IOAudioMonitor

---

Sources/Codec/AudioCodecSettings.swift

fixed https://github.com/shogo4405/HaishinKit.swift/issues/1269

fixed Encoder client can't handle 1031-byte packet!

---

Sources/Media/IOUIScreenCaptureUnit.swift

- Migration frameInterval to preferredFramesPerSecond.

Migration frameInterval to IOUIScreenCaptureUnit#preferredFramesPerSecond.

---

Sources/RTMP/RTMPStream.swift

Rename createMetadata to makeMetadata

---

Sources/Media/IOAudioUnit.swift
Sources/Media/IOMixer.swift
Sources/Media/IOVideoUnit.swift
Sources/RTMP/RTMPMuxer.swift
Sources/RTMP/RTMPStream.swift

- https://github.com/shogo4405/HaishinKit.swift/pull/1000 This adjustment was more specific to the RTMP layer rather than affecting the entire system, so it has been moved there.

Revised the lipSync cinematic.

---

README.md
Sources/Media/HKView.swift
Sources/Media/IOAudioCaptureUnit.swift
Sources/Media/IOAudioUnit.swift
Sources/Media/IOMixer.swift
Sources/Media/IOVideoCaptureUnit.swift
Sources/Media/IOVideoUnit.swift
Sources/Net/NetStream.swift

- Support tvOS17.0 for AVCaptureSession.
expected)

Availabe tvOS17.0 publish feature.

---

HaishinKit.xcodeproj/project.pbxproj
Package.swift
Sources/Extension/AVCaptureDevice+Extension.swift
Sources/Extension/AVCaptureDevice.Format+Extension.swift
Sources/Extension/AVCaptureSession+Extension.swift
Sources/Extension/AVCaptureSession.Preset+Extension.swift
Sources/Extension/AVFrameRateRange+Extension.swift
Sources/Media/IOAudioCaptureUnit.swift
Sources/Media/IOAudioUnit.swift
Sources/Media/IOCaptureUnit.swift
Sources/Media/IOMixer.swift
Sources/Media/IOVideoCaptureUnit.swift
Sources/Media/IOVideoUnit.swift
Sources/Media/MTHKView.swift
Sources/Media/PiPHKView.swift
Sources/Net/NetStream.swift
Sources/Net/NetStreamDrawable.swift
Sources/RTMP/RTMPStream.swift

- I've made it compile for visionOS for now. I haven't tested the functionality yet.

Support visionOS.

---

Examples/iOS/LiveViewController.swift
Examples/iOS/PlaybackViewController.swift
Examples/iOS/VideoAdaptiveNetBitRateStrategy.swift
HaishinKit.xcodeproj/project.pbxproj
README.md
Sources/Codec/VTSessionMode.swift
Sources/Codec/VideoCodec.swift
Sources/Codec/VideoCodecSettings.swift
Sources/MPEG/TSWriter.swift
Sources/Media/IOAudioUnit.swift
Sources/Net/NetBitRateStrategyConvertible.swift
Sources/Net/NetStream.swift
Sources/RTMP/RTMPConnection.swift
Sources/RTMP/RTMPMuxer.swift
Sources/RTMP/RTMPStream.swift
Tests/Media/IOMixerTests.swift

- I have added default interfaces and implementations for bitrate control.

Support the NetBitRateStrategy.

---

Examples/iOS/AudioCapture.swift
Examples/iOS/LiveViewController.swift
Examples/iOS/PlaybackViewController.swift
Examples/iOS/VideoAdaptiveNetBitRateStrategy.swift
HaishinKit.xcodeproj/project.pbxproj
Sources/Codec/AudioCodec.swift
Sources/Extension/AVAudioPCMBuffer+Extension.swift
Sources/Extension/AVAudioTime+Extension.swift
Sources/Extension/CMTime+Extension.swift
Sources/MPEG/TSWriter.swift
Sources/Media/IOAudioMonitor.swift
Sources/Media/IOAudioResampler.swift
Sources/Media/IOAudioRingBuffer.swift
Sources/Media/IOAudioUnit.swift
Sources/Media/IOMixer.swift
Sources/Media/IORecorder.swift
Sources/Net/NetStream.swift
Sources/RTMP/RTMPMessage.swift
Sources/RTMP/RTMPMuxer.swift
Tests/MPEG/TSReaderTests.swift
Tests/Media/IOAudioResamplerTests.swift

- I added a friendly interface to AVAudioEngine.

Add stream.appendAudioBuffer interface.

---

SRTHaishinKit/SRTStream.swift
Sources/Net/NetStream.swift

- I removed the attachRawMedia because I made it distinguishable through NetStream.videoInputFormat or NetStream.audioInputFormat.

Remove SRTStream.attachRawMedia/detachRawMedia.

---

Sources/Media/IOVideoMixer.swift
Sources/Media/IOVideoUnit.swift

- This fixed the performance degradation of CIContext caused by a bug in the 1.7.x.
- fixed the issue that was causing crashes in certain use cases.
- https://github.com/shogo4405/HaishinKit.swift/issues/1175

Performance improvements related to CIContext

---

Sources/Media/IOVideoMixer.swift

- fixed https://github.com/shogo4405/HaishinKit.swift/issues/994

fixed Please change Set<VideoEffect> to array. 

---

SRTHaishinKit/SRTStream.swift
Sources/Net/NetStream.swift
Sources/RTMP/RTMPStream.swift

- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1347

Corrected the implementation of the readyState.

---

Examples/iOS/IngestViewController.swift
Sources/IO/IOVideoMixer.swift
Sources/IO/IOVideoUnit.swift
Sources/IO/MultiCamCaptureSettings.swift

- Due to the switching cost with attachCamera, I have opted for a less costly method.
- refs https://github.com/shogo4405/HaishinKit.swift/issues/1348

Seamlessly handle the mixing of multiple cameras.

---

Sources/Extension/AVAudioTime+Extension.swift

- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1363
- fixed the issue where recording was not working as intended when downsampling and similar processes were applied.

Fix CMTime to AVAudioTime.

---

README.md

I found some typos of README.md :)

Fix: fix some typos

---

Sources/IO/IOAudioResampler.swift
Sources/IO/IOAudioRingBuffer.swift

This is a bugfix for #1384. Sometimes timescale of `CMSampleBuffer` isn't equal to the sample rate. For example, when ReplayKit sends `audioApp` sample buffers on iPhone 11 Pro Max with iOS 17.4. This PR adds an additional check to make sure timescale equals to the sample rate. If it does not, it will be recalculated like:
> new value = old value * sample rate / timescale
For example, a buffer with time stamp of:
> ▿ CMTime
>   - value : 44373327429041
>   - timescale : 1000000000
With current sampleRate 44100 will be recalculated to:
> ▿ CMTime
>   - value : 1956863739
>   - timescale : 44100
It might be good to keep the higher timescale for more accurate output timestamps, but it requires bigger rewrite of the ring buffer and resampler. 

Implement timestamp recalculation for audio buffers

---

Sources/RTMP/RTMPStream.swift

- A workaround option is provided for sending @setDataFrame with RTMPChunk.ZERO when necessary for certain services.
- refs https://github.com/shogo4405/HaishinKit.swift/pull/1388
```
send(
handlerName: "@setDataFrame",
arguments: "onMetaData", metadata,
isResetTimestamp: true
)
```

Add workground feature RTMPStream.send.

---

.github/workflows/review.yml

- Update review GitHub workflow.

Update review workflow.

---

HaishinKit.podspec

- Configuration for visionOS support for CocoaPods.
- Waiting for fix issue, https://github.com/CocoaPods/CocoaPods/issues/12118

CocoaPods visionOS supports

---

Sources/IO/IOAudioUnit.swift

- Fixed issue with audio playback in SRT.
- https://github.com/shogo4405/HaishinKit.swift/discussions/1398

Fixed issue with audio playback in SRT.

---

Examples/iOSSwiftUI/Model/ViewModel.swift
HaishinKit.xcodeproj/project.pbxproj
Sources/RTMP/RTMPMuxer.swift
Sources/RTMP/RTMPStream.swift
Sources/RTMP/RTMPTimestamp.swift
Tests/RTMP/RTMPTimestampTests.swift

- Fixed https://github.com/shogo4405/HaishinKit.swift/issues/1412

Improve handling of RTMP timestamps.

---

Cartfile
HaishinKit.podspec
Package.swift
README.md

Bump up Logboard to 2.5.0

---

Examples/iOS/IngestViewController.swift
Examples/iOS/Screencast/SampleHandler.swift
Examples/macOS/CameraIngestViewController.swift
README.md
Sources/IO/IOAUAudioMixer.swift
Sources/IO/IOAudioMixer.swift
Sources/IO/IOAudioUnit.swift
Sources/IO/IOStream.swift
Sources/IO/IOUnit.swift
Sources/IO/IOVideoCaptureUnit.swift
Sources/IO/IOVideoMixer.swift
Sources/IO/IOVideoMixerSettings.swift
Sources/IO/IOVideoUnit.swift

- With the availability of multiple audio input systems, I have renamed "channels" to "tracks."

Rename property channel to track.

---

Examples/iOS/NetStreamSwitcher.swift
SRTHaishinKit/SRTStream.swift
Sources/IO/IOAudioMixer.swift
Sources/IO/IOAudioMixerByMultiTrack.swift
Sources/IO/IOAudioMixerBySingleTrack.swift
Sources/IO/IOAudioUnit.swift
Sources/IO/IOMixer.swift
Sources/IO/IOStream.swift
Sources/IO/IOStreamObserver.swift
Sources/IO/IOVideoMixer.swift
Sources/IO/IOVideoUnit.swift
Sources/RTMP/RTMPStream.swift
Tests/IO/IOAudioMixerByMultiTrackTests.swift
Tests/IO/IOAudioMixerBySingleTrackTests.swift

- Retrieval of input formats for each track.
- Retrieval of input data through delegate methods.

Change IOStream's inputFormat to inputFormats.

---

Sources/IO/IOAudioMixer.swift
Sources/IO/IOAudioMixerByMultiTrack.swift
Sources/IO/IOAudioMixerBySingleTrack.swift
Sources/IO/IOAudioUnit.swift
Sources/IO/IOStream.swift
Sources/IO/IOVideoMixer.swift
Sources/IO/IOVideoMixerSettings.swift
Sources/IO/IOVideoUnit.swift
Sources/RTMP/RTMPStream.swift
Tests/IO/IOAudioMixerByMultiTrackTests.swift
Tests/IO/IOAudioMixerBySingleTrackTests.swift

- Migrated the mute functionality from IOStream to mixer-related classes.

Refactoring for muted functionalities.

---

Sources/Extension/AVAudioPCMBuffer+Extension.swift
Sources/IO/IOAudioMixerTrack.swift

- I have added a volume adjustment feature for audio tracks. The volume can be specified with a value between 0.0 and 1.0.
```
stream.audioMixerSettings.tracks[0]?.volume = 0.1
```

Add volume control feature by track.

---

Examples/iOS/AudioCapture.swift
Sources/IO/IOAudioMixerByMultiTrack.swift
Sources/IO/IOAudioMixerBySingleTrack.swift
Sources/IO/IOTellyUnit.swift

- Fixed memory leak IOAudioMixer classes.
- I forgot to add "weak" to the delegate, which caused a memory leak.

fixed memory leak IOAudioMixer classes.

---

Sources/RTMP/RTMPStream.swift

[TBA] refs #1410 add metadata to duration.

---

Sources/Util/AVAudioUtil.swift

Fixed #1444

---

HaishinKit.xcodeproj/project.pbxproj
Sources/IO/IOAudioTime.swift
Sources/IO/IOStream.swift
Sources/IO/IOTellyUnit.swift
Sources/IO/MediaLink.swift
Sources/Util/TypedBlockQueue.swift

- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1454

#1454 fix playerNode dead lock.

---

.github/workflows/review.yml

- Bump to Xcode up 15.4 on GitHub Action.

Update GitHub Action to use Xcode15.4

---

SRTHaishinKit/SRTConnection.swift
Vendor/SRT/build-visionos.sh
Vendor/SRT/libsrt.xcframework/Info.plist

- XROS_TARGET=1.2 → 1.0
- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1481

Update libsrt.framework and SRTHaishinKit

---

Sources/Screen/ScreenObject.swift

- https://github.com/shogo4405/HaishinKit.swift/pull/1449.
- Should have made it `open` for users to customize.

Make open ScreenObject.

---

Sources/ISO/TSWriter.swift

Fixed After fist live audio does not have a program SRTHaishinKit

---

Sources/RTMP/AMFFoundation.swift
Sources/RTMP/RTMPSharedObject.swift

- I am refactoring to ensure compatibility with Swift 6.0 without introducing any breaking changes.

nonisolated(unsafe) property ASTypedObject.decoders and RTMPSharedObject.remoteSharedObjects

---

Examples/iOS/Preference.swift
HaishinKit.xcodeproj/project.pbxproj
Sources/Extension/CMSampleBuffer+Extension.swift
Tests/Extension/CMSampleBuffer+ExtensionTests.swift

- fixed #1515
```
2024-19-07 01:27:06.603 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] append(_:) > true
2024-19-07 01:27:06.643 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] append(_:) > false
2024-19-07 01:27:06.680 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] append(_:) > false
2024-19-07 01:27:06.722 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] append(_:) > false
2024-19-07 01:27:06.764 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] append(_:) > false
2024-19-07 01:27:06.809 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] append(_:) > false
2024-19-07 01:27:06.844 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] append(_:) > false
2024-19-07 01:27:06.890 [Info] [com.haishinkit.HaishinKit] [RTMPMuxer.swift:171] …
```

fixed #1515 Every FLV frame has key type

---

Sources/IO/IOStream.swift
Sources/IO/MediaLink.swift

- fix the issue where unintended buffering time increases during playback, among other issues.

fix the issue where unintended buffering increases.

---

Sources/Codec/VideoCodec.swift

- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1599

Encoding is now processed when PTS increases in monotonic time.

---

Sources/Extension/AVCaptureSession+Extension.swift
Sources/IO/IOAudioMixerByMultiTrack.swift
Sources/IO/IOAudioMonitor.swift
Sources/IO/IOAudioRingBuffer.swift
Sources/Screen/Shape.swift
Tests/RTMP/RTMPTimestampTests.swift

- Migration https://github.com/shogo4405/HaishinKit.swift/pull/1613 to 1.9.x

fix can't compile macCatalyst 1.9.x

---

HaishinKit/Sources/HKStream/HKStreamRecorder.swift

- I have fixed a migration error to 2.0.x.
- https://github.com/shogo4405/HaishinKit.swift/pull/1561 

Fix Add the movieFragmentInterval value to the recording feature 2.0.x

---

HaishinKit/Sources/Mixer/MediaMixer.swift

- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1629

Fixed crash when enter background.

---

HaishinKit/Sources/Util/Runner.swift

- Adding async makes it more convenient, so I will include it.

Update protocol AsyncRunner.

---

HaishinKit/Sources/HKStream/HKIncomingStream.swift
HaishinKit/Sources/HKStream/MediaLink.swift
HaishinKit/Sources/ISO/TSReader.swift
HaishinKit/Sources/ISO/TSWriter.swift
SRTHaishinKit/Sources/SRT/SRTConnection.swift
SRTHaishinKit/Sources/SRT/SRTStream.swift

- refs https://github.com/shogo4405/HaishinKit.swift/issues/1651
- I fixed the issue as there were leaks not only in MediaMixer but elsewhere as well.
- SRTConnection
- SRTStream

fixed MemoryLeak issue SRTConnection, SRTStream.

---

.github/workflows/review.yml

- Updated the GitHub Action stack.

Bump to up GitHub Action's stack.

---

HaishinKit/Sources/Mixer/MediaMixer.swift

- Fix for a crash issue when transitioning to the background in Swift 6 mode.
- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1663

Fix for a crash issue when transitioning to the background in Swift 6 mode.

---

HaishinKit/Sources/HKStream/HKStreamRecorder.swift

- fixed it because the method name did not follow the naming conventions.

Rename a HKStreamRecord method name.

---

Examples/iOS/AppDelegate.swift
HaishinKit/Sources/RTMP/RTMPSocket.swift

- fixed memory-leaks an RTMPSocket.

fixed memory-leaks an RTMPSocket.

---

Sources/IO/IOVideoMixer.swift

- Fixed an issue where screen rendering could potentially get locked.

fixed an issue where screen rendering could potentially get locked.

---

Sources/ISO/PacketizedElementaryStream.swift

- backport 1.9.x
- https://github.com/shogo4405/HaishinKit.swift/pull/1678
- refs https://github.com/shogo4405/HaishinKit.swift/issues/1677

fixed large PES packets could be dropped.

---

HaishinKit/Sources/RTMP/RTMPFoundation.swift
HaishinKit/Sources/RTMP/RTMPMessage.swift
HaishinKit/Sources/RTMP/RTMPStream.swift
HaishinKit/Sources/RTMP/RTMPTimestamp.swift

Improved viewing stability when using H.264 Main Profile or HEVC with RTMP.
- refs https://github.com/shogo4405/HaishinKit.swift/issues/1676

Improve CTS calculation.

---

HaishinKit/Sources/RTMP/RTMPFoundation.swift
Package.swift
SRTHaishinKit/Sources/SRT/SRTError.swift
SRTHaishinKit/Sources/SRT/SRTSocket.swift
SRTHaishinKit/Sources/SRT/SRTSocketOption.swift
SRTHaishinKit/Tests/Extension/Data+Extension.swift
SRTHaishinKit/Tests/SRT/SRTSocketOptionTests.swift

1. Updated to use the latest SRT API.
1. Fixed to allow the use of int types and others in SRT query parameters.

Made it possible to set SRT options from the query.

---

Examples/Preference.swift
SRTHaishinKit/README.md
SRTHaishinKit/Sources/SRT/SRTConnection.swift
SRTHaishinKit/Sources/SRT/SRTSocket.swift
SRTHaishinKit/Sources/SRT/SRTStream.swift
SRTHaishinKit/Tests/SRT/SRTSocketOptionTests.swift

- Changed to retrieve network statistics from the SRT API.
- Fixed to properly close when the SRT host server ABENDs.

Improved SRT connection stability.

---

SRTHaishinKit/Sources/SRT/SRTConnection.swift
SRTHaishinKit/Sources/SRT/SRTMode.swift
SRTHaishinKit/Sources/SRT/SRTSocket.swift
SRTHaishinKit/Sources/SRT/SRTSocketOption.swift
SRTHaishinKit/Tests/SRT/SRTConnectionTests.swift
SRTHaishinKit/Tests/SRT/SRTSocketOptionTests.swift

- Modified to update statistical information in SRT listener mode.
- Support `transtype` options.

Enhanced SRT listener mode functionality.

---

SRTHaishinKit/Sources/SRT/SRTConnection.swift
SRTHaishinKit/Sources/SRT/SRTStream.swift

- fixed SRTConnection memory-leak

fixed SRTConnection memory-leak.

---

HaishinKit/Sources/Docs.docc/E-RTMP.md
HaishinKit/Sources/Docs.docc/index.md
HaishinKit/Sources/RTMP/RTMPConnection.swift

- Support [Enhancing NetConnection connect Command](https://github.com/veovera/enhanced-rtmp/blob/main/docs/enhanced/enhanced-rtmp-v2.md#enhancing-netconnection-connect-command)

Support Enhancing NetConnection connect Command.

---

Examples/iOS/IngestViewController.swift
Examples/iOS/Main.storyboard

* Fix typo (audioMonoStereoSegmentCOntrol -> audioMonoStereoSegmentControl)

Fix typo (audioMonoStereoSegmentCOntrol -> audioMonoStereoSegmentControl)

---

HaishinKit/Tests/Mixer/AudioMixerByMultiTrackTests.swift
HaishinKit/Tests/Mixer/AudioMixerBySingleTrackTests.swift
HaishinKit/Tests/Mixer/AudioMixerTrackTests.swift
HaishinKit/Tests/Mixer/MediaMixerTests.swift
HaishinKit/Tests/Screen/VideoTrackScreenObjectTests.swift

- Update AudioMixer test cases.

Update AudioMixer test cases.

---

HaishinKit/Sources/HKStream/HKStream.swift
RTMPHaishinKit/Sources/RTMP/RTMPStream.swift
SRTHaishinKit/Sources/SRT/SRTStream.swift

- fix typo BitRateStorategy -> BitRateStrategy.

fix typo BitRateStorategy -> BitRateStrategy.

---

Examples/Preference.swift
HaishinKit/Sources/Session/Session.swift
HaishinKit/Sources/Session/SessionBuilder.swift
RTMPHaishinKit/Sources/RTMP/RTMPSession.swift
SRTHaishinKit/Sources/SRT/SRTSession.swift

- Implement a retry mechanism for the Session API.

Add retry RTMPConneciton.

---

Examples/iOS/IngestViewModel.swift
HaishinKit/Sources/Mixer/MediaMixer.swift

> This behavior is planned to be the default in the 2.1.x series.
- https://github.com/HaishinKit/HaishinKit.swift/pull/1642

Remove start capture manually option.

---

HaishinKit/Sources/Codec/VideoCodecSettings.swift

- Rename isHardwareEncoderEnabled to isHardwareAcceleratedEnabled.

Rename isHardwareEncoderEnabled to isHardwareAcceleratedEnabled.

---

RTMPHaishinKit/Sources/RTMP/RTMPStreamInfo.swift

- Now conforms to Sendable RTMPStreamInfo.
- Fixed: https://github.com/HaishinKit/HaishinKit.swift/discussions/1772

Now conforms to Sendable RTMPStreamInfo.

---

.github/ai-moderator.yml

- As an experiment, I’m introducing [AI Moderator](https://github.com/github/ai-moderator) to address issues that don’t follow the template.

install: AI Issue and Comment Moderator
