- Sources/HTTP/HTTPService.swift
Required for it to be a valid HLS stream
> Add status code in http response

- Sources/ISO/TSWriter.swift
Library periodically crashes with "out of range" exception:
> Fixed crash in TSWriter

- Sources/Codec/AVCEncoder.swift
This feature allows the developers to switch the PixelTransfer ScalingMode property thought videoSettings on the RTMPStream object. This cropped up as a use case (as discussed in #169) when the RTMP server ingests performs incoming stream encoding and has issues with the stream resolution changing which was a use case solution for camera rotation while streaming (as discussed in #147).
The library still keeps the default Trim behaviour of the PixelTransfer, but allows for all the other modes available for the property.
> Makes scaleMode property of encoder a configurable property

- Sources/HTTP/HTTPRequest.swift
- Sources/ISO/ProgramSpecific.swift
- Sources/ISO/TSWriter.swift
- Sources/Util/Mutex.swift
Hi, @shogo4405 
Thanks for the awesome lib!
I found and patched some crashing bugs below.
```
1. ProgramSpecific.swift
Cause: Bad access to array via concurrent thread
Patch: Thread lock using mutex
2. TSWriter.swift
Cause: Raised an exception when invoke FileHandle.synchronizeFile function
Patch: Catch exception by nstry
3. HTTPRequest.swift
Cause: Raised index out of range exception
Patch: Add guard statement before take values from bytes string
```
Please confirm this :)
> Fix crashing on ios

- Sources/RTMP/RTMPTSocket.swift
I think /idle/ requests this often sometimes causes red5 server to close the stream
> /idle/ requests are sent too often

- Sources/RTMP/RTMPTSocket.swift
On iOS 10.3 I'm constantly getting error -1005 when the request is expired
But on iOS 9 errors are varying between:
```
Error Domain=NSURLErrorDomain Code=-1017 "cannot parse response"
Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server."
Error Domain=NSURLErrorDomain Code=-1 "unknown error"
```
Retrying the request seems to help with all of them.
> expired keepalive request may cause more errors than just -1005

- Sources/RTMP/RTMPChunk.swift
```swift
// 2~63 -> 1B
// +-+-+-+-+-+-+-+-+
// |fmt|   cs id   |
// +-+-+-+-+-+-+-+-+
// 64~319 -> 2B
// +-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-+
// |fmt|     0     |   cs id - 64  |
// +-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-+
// 64~65599 -> 3B
// +-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|
// |fmt|     1     |           cs id - 64          |
// +-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|-+-+-+-+-+-+-+-|
```
For example, `0b00111111` means chunkType = .zero, chunk stream id= 63
> Fix error when csid > 320

- Sources/Media/VideoIOComponent.swift
Asynchronous dispatch causes exception `AVCaptureSession can't stopRunning between calls to beginConfiguration / commitConfiguration`
> Dispatch synchronously if not on main queue, otherwise call without dispatch

- Sources/ISO/H264+AVC.swift
In AVC format, NAL Units are accompanied with its length in 4 bytes, big endian.
Skipping first 2 bytes is invalid, because there may be valid non-zero bytes.
In order to convert AVC format to Annex-B byte stream, the program must read all 4 bytes as length and read that bytes as NAL unit.
> Fix AVC format reading

- Platforms/iOS/ScreenCaptureSession.swift
Capturing specific Views after updates can sometimes be detrimental to the framerate. Allowing apps to determine the appropriate setting for this allows for more flexibility. Defaults to false for Window, true for Views.
> Expose afterScreenUpdates as a property.

- Platforms/iOS/ScreenCaptureSession.swift
The display link callback happens on the UI Thread (currently), so putting it here is an acceptable fix.
> Move the size calculation to UI thread

- Sources/RTMP/RTMPConnection.swift
Because of the space in this url string the URL construction always fails and the ! operator results in a crash.
> Remove extraneous space from auth command url.

- Sources/Media/VideoIOComponent.swift
After using setPointOfInterest to focus, autofocus is not working anymore. 
by changing the focus- and exposuremode to continuousAuto it now works just like native ios camera.
It will focus at a selected point, but when you move the camera, autofocus takes over.
> fixed autofocus after focussing point of interest

- Sources/RTMP/RTMPSharedObject.swift
This fixes a minor compilation error with Swift 4.1.
> Fix Swift 4.1 compilation error.

- Sources/ISO/TSWriter.swift
Using HLS with TSWriter, I found the "EXT-X-TARGETDURATION" is incorrect sometime at iPhone device.
```
#EXTM3U
#EXT-X-VERSION: 3
#EXT-X-MEDIA-SEQUENCE: 0
#EXT-X-TARGETDURATION: 6
#EXTINF: 6.00054620800074,
280238.ts
#EXTINF: 6.00050887500402,
280244.ts
#EXTINF: 6.00048975000391,
```
According to https://tools.ietf.org/html/draft-pantos-http-live-streaming-08#section-3.4.2:
```
The EXT-X-TARGETDURATION tag specifies the maximum media segment
duration.  The EXTINF duration of each media segment in the Playlist
file MUST be less than or equal to the target duration.  This tag
MUST appear once in the Playlist file.
```
> resolve shogo4405/HaishinKit.swift#413

- Sources/Extension/URL+Extension.swift
Fixes #472 - username and password is no longer included in `tcUrl`.  URLComponents is used instead of string replacement in URL extension's `absoluteWithoutAuthenticationString` computed property.  Please see #472 for a description of the cause of the bug.
> username and password is no longer inadvertently included in `tcUrl`

- Sources/Media/VideoIOComponent.swift
Resolves #505 
The VideoIOComponent.orientation value can be different to the `drawable.orientation` value. This happens when RTMPStream.orientation is set and the drawable is nil.
With this change, after the drawable is created, its orientation is set to match the RTMPStream orientation.
> drawable orientation to match stream when created

- Sources/Media/AVMixer.swift
- Sources/Media/VideoIOComponent.swift
There are many reports all over the Internet saying that the internal iPhone camera stabilization system is jamming external ones, for example, it acts against a gimbal stabilization method.
I'd like to use my app with a gimbal such as this one: https://www.dji.com/uk/osmo-mobile-2 but currently the results are shaky because of iOS stabilization behaviour.
Here is a PR to give the possibility to deactivate it within HaishinKit.swift.
Usage:
```
rtmpStream.captureSettings = [
"sessionPreset": AVCaptureSession.Preset.hd1280x720.rawValue,
"continuousAutofocus": true,
"continuousExposure": true,
"stabilization": false
]
```
> Add the ability to disable the iPhone camera stabilization

- Sources/Media/VideoIOComponent.swift
- Sources/Net/NetStream.swift
- Sources/RTMP/RTMPStream.swift
Follow up to PR #506.
This fixes #505.
The drawable's orientation was still getting out of sync. With this PR, the initial orientation can be set using a static variable. It was also necessary to always update the drawable's orientation when orientation is set.
I don't know what was causing the orientations to get out of sync but these changes fix it for me.
> static variable to set default orientation & always update drawable

- Sources/FLV/FLVReader.swift
Apple released XCode 10.2 this morning.
You will see the error below in file `FLVReader.swift` when you build project with XCode 10.2.
`Mutating method 'readData' may not be used on immutable value 'tag'`
> fix error when run in xcode10.2

- Sources/RTMP/RTMPConnection.swift
- Tests/RTMP/RTMPConnectionTests.swift
`timer` instance holds the `RTMPConnection` instance so it won't be deallocated after `close()` gets called.
> Make RTMPConnection be deallocated on close()

- HaishinKit.xcodeproj/project.pbxproj
- Sources/RTMP/RTMPStream.swift
- Tests/RTMP/RTMPStreamTests.swift
`RTMPStream` keeps waiting for the state change when the `readyState` is `.initialized`. It prevents  `RTMPStream` from closing the connection so it won't be deallocated after `close()` gets called.
This PR makes `RTMPStream` stop waiting for the state change when the stream is about to close so it can be deallocated.
> Make RTMPStream be deallocated on close() when the readyState is .initialized

- Sources/RTMP/RTMPConnection.swift
- Sources/RTMP/RTMPStreamDelegate.swift
Busy working on a adaptive bitrates, `RTMPStreamDelegate` provides a way to lower the bitrate however I need a way to up the bitrate and I think this solution might work.
Usage:
```swift
let minBitrate: UInt32 = 300 * 1024
let maxBitrate: UInt32 = 2500 * 1024
let incrementBitrate: UInt32 = 512 * 1024
class MyRTMPStreamDelagate: RTMPStreamDelegate {
@objc var onBWStatusChange: RCTDirectEventBlock?
func didPublishInsufficientBW(_ stream: RTMPStream, withConnection: RTMPConnection) {
guard var videoBitrate = stream.videoSettings["bitrate"] as? UInt32 else { return }
print("didPublishInsufficientBW \(videoBitrate)")
videoBitrate = UInt32(videoBitrate / 2)
if videoBitrate < minBitrate {
videoBitrate = minBitrate
}
stream.videoSettings["bitrate"] = videoBitrate
}
func didPublishSufficientBW(_ …
```
> Add did publish sufficient BW

- Sources/RTMP/RTMPStream.swift
Added check to filename length with respect to system var FILENAME_MAX, so it shouldn't exceed maximum length provided by iOS
> Fixed issue of video file not being saved if filename exceeds max size limit

- Sources/RTMP/RTMPMuxer.swift
動画のペイロードにおいて、Composition Timeが常に0となってしまっていましたが、この修正により正しい値がセットされるようになります。
> Fix invalid composition time of video payload

- Sources/RTMP/RTMPSocket.swift
Right now event handlers are allocated only once in `RTMPSocket.init`, but deallocated every time `NetSocketCompatible.deinitConnection(isDisconnected:)` is called. It leads `RTMPSocket` unable to observe events from socket after first disconnection. 
This PR contains a fix to this issue and reinitializes event handlers on every `connect(withName:port:)` call.
> Recreate event handlers on connection

- Sources/ISO/TSWriter.swift
- Sources/Media/AVRecorder.swift
Allow segment duration of a transport stream to be passed to the
TSWriter constructor.
Making the segment duration configurable allows for shorter data
callback intervals which is useful for application which require lower
latency between starting the stream and receiving first bytes (e.g.
SRT).
* Add DefaultAVRecorderDelegate.FileType enum with .mp4 and .mov cases
* Add DefaultAVRecorderDelegate.fileType property
* Default DefaultAVRecorderDelegate.fileType to .mp4
* Initialize AVAssetWriter with proper AVFileType based on fileType
* Take FileType in DefaultAVRecorderDelegate constructor
> TSWriter configurable segment duration and allow both mp4 and mov recordings from DefaultAVRecorderDelegate

- Sources/RTMP/RTMPMessage.swift
- Sources/RTMP/RTMPSharedObject.swift
When trying to connect to a shared object with persistence, I was receiving the following error from server:
`SharedObject.BadPersistence`
This PR fixes this issue.
> Fixed getting shared object with persistence

- Sources/Util/Setting.swift
READMEではmaxKeyFrameIntervalDurationをIntで設定していますが、Doubleに変換するところで捨てられて設定されていませんでした。
> maxKeyFrameIntervalDurationがIntだと設定されない

- Platforms/iOS/VideoIOComponent+Extension.swift
- Sources/Net/NetStreamRenderer.swift
- Sources/RTMP/RTMPStreamInfo.swift
Swift Package Manager in Xcode 11 will fail because some import statements are missing. This PR fixes that.
> Fix SPM support

- Platforms/iOS/HKView.swift
When HKView's `attachStream` is called, it uses the `lockQueue` to set the `stream.mixer.videoIO.renderer`, but this results in the didSet of that property trying to set HKView's `orientation` property, which accesses the CALayer `layer` property while on `lockQueue`.
This PR ensures that the `layer` property is accessed synchronously on the main queue. Camera output appears much faster on view load, Xcode's Main Thread Checker no longer complains.
> Fix main thread access in HKView

- Sources/ISO/PacketizedElementaryStream.swift
11 = both present, 01 = forbidden, 10 = only PTS, 00 = no PTS or DTS (according to https://en.wikipedia.org/wiki/Packetized_elementary_stream )
> Fix PESPTSDTSIndicator

- Sources/Media/VideoIOComponent.swift
This PR fixes an issue where `VideoIOComponent` may cause the renderer's life cycle management to get messed up.
- Push a new view controller that contains a `HKView` (or any other renderer, so a streaming view controller) onto the navigation stack
- Pop the view controller from the navigation stack
- Check life cycle on `deinit`, the view controller is destroyed as expected, but it takes quite a long time for the `HKView` to get destroyed
- If you try to push another streaming view controller onto the navigation stack before the earlier one's `HKView` is destroyed, then the new one gets stuck 
I tested this from the branch by rapidly pushing a view controller that contains a `HKView` onto the navigation stack from a list item and popping it instantly and pushing a new one and it seems to …
> Fix renderer life cycle issue

- Platforms/iOS/GLHKView.swift
- Platforms/iOS/MTHKView.swift
I add `isMirrored` property for GLHKView and MTHKView, so the view can be mirrored when `rtmpStream.captureSettings[.isVideoMirrored]` is set true.
I did not add a mirror button on the UI, because there's no button for setting `rtmpStream.captureSettings[.isVideoMirrored]` to true yet. We may need manual testing for this part, or I can add the UI later if needed.
I hope this new property is clear and useful enough.
> Feature: add property `isMirrored` in MTHKView and GLHKView

- Sources/Codec/H264Encoder.swift
- Sources/ISO/TSWriter.swift
**背景**
HTTPStreamのTSWriterで行っているように、以下のような独自のNetStreamを定義し、H.264にエンコードされた後のCMSampleBufferを参照したいが、VideoEncoderDelegateがpublicではないため利用できない。
```swift
open class FooStream: NetStream {
private let fooPacketizer: FooBacketizer
...
open func publish(_ name: String?) {
self.mixer.startEncoding(delegate: fooPacketizer)
self.mixer.startRunning()
}
}
class FooPacketizer {
}
extension FooPacketizer: VideoEncoderDelegate {
public func didSetFormatDescription(video formatDescription: CMFormatDescription?) {
...
}
public func sampleOutput(video sampleBuffer: CMSampleBuffer) {
...
}
}
extension FooPacketizer: AudioConverterDelegate {
public func didSetFormatDescription(audio formatDescription: CMFormatDescription?) {
...
}
public func sampleOutput(audio data: UnsafeMutableAudioBufferListPointer, …
```
> H.264にエンコードされた後のCMSampleBufferを参照可能にする

- Sources/RTMP/RTMPConnection.swift
- Sources/RTMP/RTMPStream.swift
- Sources/RTMP/RTMPStreamDelegate.swift
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html
> Allow Coding Guidelines for Cocoa Delegate method section

- Sources/Media/VideoIOComponent.swift
Change to keep device settings for focusMode and exposureMode when using PointOfInterest.
Currently using PointOfInterest for focus and exposure always overrides with the continuous modes.
It should be possible to use pointOfInterest with both continues and auto modes.
> Keep focus and exposure modes when using pointOfInterest

- Package.swift
Swift Package Manager misses one of the new directories during installation of the latest commit, add it to Package.swift.
Tested on Xcode 12.4 using SPM installation.
> Add new directory to Package.swift.

- Sources/Media/MTHKView.swift
When using MTHKView with _resizeAspectFill_ videoGravity, the x origin is set incorrectly with the _isMirrored_ option (tested on iPad Pro landscape).
Applying the mirror effect before resizing the image fixes the issue.
> fix: render view x origin when using isMirrored option with MTHKView

- Sources/HTTP/HLSService.swift
`HLSService`を利用して立てたiPhone上のWebサーバーのルートドキュメントにmacOSのSafariでアクセスすると、`HTTPService#defaultDocument`のhtmlがhtmlレンダリングされない不具合を見つけました。
- macOS Big Sur バージョン 11.6
Safari バージョン15.0 (16612.1.29.41.4, 16612)
- Xcode13.1
- iPhone 12 Pro iOS 15.1
- コード
[RFC 7230](https://triple-underscore.github.io/RFC7230-ja.html#p.status-line)に基づいて、ステータスコードを返却するように修正。
- Safari
- Chrome
> fix html was not rendered in Safari

- Sources/HTTP/HTTPService.swift
`HLSService`のサブクラスで`HLSService#defaultDocument`をオーバーライドできるが、superクラス側が使用されてしまうため、オーバーライド側が使用されるように変更しました。
- コード
- 事象
> overridden defaultDocument to be used

- Sources/HTTP/M3U.swift
`HLSService`クラスが生成したプレイリストに[Video.js](https://videojs.com/)でアクセスすると、`duration`の解析に失敗し、映像が表示されない。
<details>
<summary>アプリコード</summary>
```
class ViewController: UIViewController {
let stream = HTTPStream()
let service = HLSService(
domain: "local",
type: HTTPService.type,
name: "",
port: 80
)
override func viewDidAppear(_ animated: Bool) {
super.viewDidAppear(animated)
switch AVCaptureDevice.authorizationStatus(for: .video) {
case .notDetermined:
Task {
if await AVCaptureDevice.requestAccess(for: .video) {
setup()
}
}
case .authorized:
setup()
case .denied, .restricted:
break
@unknown default:
fatalError("hoge")
}
}
func setup() {
service.addHTTPStream(stream)
let deviceDiscoverySession = AVCaptureDevice.DiscoverySession(
deviceTypes: [AVCaptureDevice.DeviceType.builtInWideAngleCamera], …
```
> fix Video.js fails to parse duration in a playlist

- Sources/Media/PiPHkView.swift
I got these build errors because UIKit-related definitions are missing
- Environment
- MacBook Pro (13-inch, M1, 2020), Apple M1 chip
- macOS 12.4
- Xcode 13.4.1 (13F100)
- Build target: `.iOS(.v14)`
- HaishinKit 1.2.5
- Import HaishinKit via Swift Package Manager
- Add `import UIKit` to PiPHkView.swift
> Add UIKit import to PiPHkView

- Sources/RTMP/RTMPConnection.swift
- Sources/RTMP/RTMPStream.swift
- Rename a RTMPStreamDelegate
- Remove a RTMPStreamDelegate default implement.
> Remove RTMPStreamDelegate default implement.

- Examples/iOS/LiveViewController.swift
- Examples/iOS/PlaybackViewController.swift
- Examples/iOSSwiftUI/Model/ViewModel.swift
- Sources/Media/AVRecorder.swift
- Sources/Net/NetStream.swift
- Sources/RTMP/RTMPStream.swift
- Support local recording without publish.
```
rtmpStream.publish("streamName", .localRecord)
/// stop-recording rtmpStream.publish("streamName") or rtmpStream.close()
```
```
rtmpStream.startRecording()
/// rtmpStream.stopRecording()
```
> Support local recording without publish.

- Sources/RTMP/RTMPStream.swift
Hello, 
Since this PR https://github.com/shogo4405/HaishinKit.swift/pull/1035 local recording is not really related with publishing. 
This PR let the user decide when the recording should be stopped. 
Goal : allow record even on a network cut
> Remove stop recording on stop publishing

- Sources/RTMP/RTMPMuxer.swift
Fix invalid timestamps messages from ffplay
```
[flv @ 0x13b716e20] Negative cts, previous timestamps might be wrong.
[flv @ 0x13b716e20] Invalid timestamps stream=1, pts=3168, dts=3201, size=176
[flv @ 0x13b716e20] Invalid timestamps stream=1, pts=3235, dts=3268, size=158
[flv @ 0x13b716e20] Invalid timestamps stream=1, pts=3301, dts=3334, size=192
[flv @ 0x13b716e20] Invalid timestamps stream=1, pts=3368, dts=3401, size=273
```
> Advanced B-Frame compatibility

- .gitignore
- Sources/Codec/VTSessionMode.swift
- Sources/Codec/VideoCodec.swift
`VideoCodec` never sets `invalidateSession` to `false`. As result, `session` is reinitialized after every `inputBuffer` call.
Some misc updates:
* Add AppCode folder to .gitignore
* Check status after setting video codec options and call appropriate delegate method
> Fix: session is reinitialized every frame

- Sources/Codec/VideoCodec.swift
`scalingMode` isn't used at the moment. This PR brings it back from older version of HaishinKit
> Bring back scaling mode setting

- Examples/iOS/LiveViewController.swift
- README.md
- Sources/Util/DeviceUtil.swift
- Remove DdeviceUtil#device(withPosition: AVCaptureDevice.Position)
- AVCaptureDevice.devices() method is deprecated.
> Remove DeviceUtil#device method.

- Sources/Net/NetStream.swift
Invert `hasAudio` and `hasVideo` values to match "muted" flag 
> Invert hasAudio and hasVideo values

- Sources/RTMP/RTMPStream.swift
Fixes #1103
Providing audio sample rate is helpful for knowing what data is coming in the stream
> Fix: add audio sample rate

- Sources/RTMP/RTMPNWSocket.swift
- fastlane/Fastfile
* RTMPNWSocket 
- Enabled SSL connection without option.
> Support "rtmps" RTMPNWSocket without setPrameter option.

- Sources/Media/Choreographer.swift
- Sources/Media/MediaLink.swift
- Fix can't playback rtmpStream.play() -> rtmpStream.close() -> rtmpStream.play().
> Can't playback rtmpStream.close() after rtmpStream.play().

- Sources/Media/IOCaptureUnit.swift
- Sources/Media/IOMixer.swift
- Sources/Util/DeviceUtil.swift
- Set a device frameRate when unsupportedDeviceActiveFormat.
- It was not possible to set the expected value 30.
> Set a device frameRate when unsupportedDeviceActiveFormat.

- Sources/Media/IOMixer.swift
- Sources/Net/NetStream.swift
- Sources/RTMP/RTMPStream.swift
> fixed #1209 AVCaptureSession startRunning] should be called from background thread.

- Sources/Codec/VTSessionMode.swift
- Sources/Codec/VideoCodec.swift
- Sources/Codec/VideoCodecSettings.swift
- Sources/Media/IOVideoUnit.swift
> fixed RTMPStream.videoSettingsに設定した値がすぐにdefaultに上書きされる

- Sources/MPEG/PacketizedElementaryStream.swift
- Sources/Media/IOMixer.swift
- fixed https://github.com/shogo4405/SRTHaishinKit.swift/issues/57
> fixed VTDecompressionSessionDecodeFrame fails with OSStatus=-12909 #57

- Sources/Extension/AVCaptureSession+Extension.swift
- Sources/Media/IOMixer.swift
- Sources/Net/NetStream.swift
- Fixed https://github.com/shogo4405/HaishinKit.swift/issues/1238
- Refes https://github.com/shogo4405/HaishinKit.swift/issues/1209
> Fix AVCaptureSession race condition.

- Sources/Codec/AudioCodecRingBuffer.swift
- Tests/Codec/AudioCodecBufferTests.swift
- Tests/SinWaveUtil.swift
I have fixed the issue where the audio signal gets corrupted when capturing stereo audio and the sample count is less than 1024 during microphone capture.
- fixed #1208
- refs #1240
> fixed break audio with stereo format.

- Sources/RTMP/RTMPNWSocket.swift
- might be fixed https://github.com/shogo4405/HaishinKit.swift/issues/1210
- There was an error in the statistical processing, and instead of measuring at a 1-second interval as intended, it was being handled with the most recent enqueued data.
> fixed the statistical processing RTMPNWSocket.

- Sources/Media/IOVideoUnit.swift
fixed the crash the order of method execution.
```
2023-08-16 00:28:53.202630+0900 Example iOS[41970:4745685] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureSession removeConnection:] <AVCaptureConnection: 0x281493da0> does not exist in this session'
*** First throw call stack:
(0x1cfd54cb4 0x1c8de83d0 0x1e9a0b228 0x1033a0068 0x103262510 0x10329d650 0x1032651e0 0x102dc4520 0x102dc6038 0x102dce0b0 0x102dcedf4 0x102ddbc74 0x22fb85ddc 0x22fb85b7c)
libc++abi: terminating due to uncaught exception of type NSException
```
**Reproduce**
```
rtmpStream.attachAudio(nil)
rtmpStream.attachCamera(nil)
if #available(iOS 13.0, *) {
rtmpStream.attachMultiCamera(nil)
}
```
**Don't reproduce**
```
rtmpStream.attachAudio(nil)
if #available(iOS 13.0, *) { …
```
> fixed the crash the order of detachCamera.

- HaishinKit.xcodeproj/project.pbxproj
- Sources/Codec/AudioCodec.swift
- Sources/Codec/AudioCodecSettings.swift
- Sources/Extension/AVAudioFormat+Extension.swift
* Feature: add multi channel audio support
This change is providing an audio layout for the `AVAudioFormat` when number for channels of the input format is more than two. `AVAudioFormat` [recommends](https://developer.apple.com/documentation/avfaudio/avaudioformat/1390106-init) using `init(streamDescription:channelLayout:)`:
>If the AudioStreamBasicDescription specifies more than two channels, this method fails and returns nil. 
>Instead, use the init(streamDescription:channelLayout:)
This PR adds a method to create a layout for non mono/stereo audio formats. It also limits maximum number of output audio channels to two in `AudioCodecSettings`. Lastly, it adds a method that creates a channel mapping and provides it to the audio converter.
I tested this change with mono, stereo and 4 …
> Support for multi-channel audio streaming

- Sources/Codec/AudioCodec.swift
- Sources/Codec/AudioCodecSettings.swift
- Tests/Codec/AudioCodecTests.swift
* Fix audio channel mapping. My previous implementation was creating a channel map of size n, where n is number of input channels. It should use number of output output channels instead.
* Expose channel map for external use
* Add channel map unit tests
> Improve audio channel mapping

- Sources/Codec/AudioCodec.swift
- Sources/Codec/VTSessionMode.swift
- Sources/Codec/VideoCodec.swift
- Sources/Media/HKView.swift
- Sources/Media/IOAudioResampler.swift
- Sources/Media/IOAudioUnit.swift
- Sources/Media/IOMixer.swift
- Sources/Media/IOUnit.swift
- Sources/Media/IOVideoUnit.swift
- Sources/Media/MTHKView.swift
- Sources/Media/PiPHKView.swift
- Sources/Net/NetStreamDrawable.swift
- Sources/RTMP/RTMPMessage.swift
- Sources/RTMP/RTMPStream.swift
- The creation condition for onMetaData was originally based on the presence of a device attachment, but it has been switched to the presence of a signal. This change allows sending metadata as expected without the need to inherit RTMPStream, even with APIs like ReplayKit or ScreenCaptureKit.
- https://github.com/shogo4405/HaishinKit.swift/pull/1074
> Creating RTMP onMetaData based on input data.

- Sources/RTMP/AMF0Serializer.swift
- Sources/RTMP/AMF3Serializer.swift
As the title says, it is handy to be able to map a CGFloat value to a Double for the purposes of encoding it in the `Serializer` types. 
This came about when the `VideoSize` type went away. It was replaced by a `CGSize` which returns `CGFloat` types for the `width` and `height` properties. In the `makeMetaData` function on an `RTMPStream`, these properties are assigned as values to keys in the dictionary: 
```
metadata["width"] = videoSettings.videoSize.width
metadata["height"] = videoSettings.videoSize.height
```
The only problem is that they fail to serialise when going through the `func serialize(_ value: Any?) -> Self` function in `AMF0Serializer`, as it doesn't handle `CGFloat` data types.
Please let me know if you foresee any issues with the proposed solution. It should be additive …
> Allow CGFloat values to be serialised.

- Examples/iOS/IngestViewController.swift
- Examples/iOS/NetStreamSwitcher.swift
- Examples/iOS/Screencast/SampleHandler.swift
- HaishinKit.xcodeproj/project.pbxproj
- SRTHaishinKit/SRTStream.swift
- Sources/Codec/AudioCodec.swift
- Sources/Codec/VideoCodec.swift
- Sources/MPEG/TSWriter.swift
- Sources/Media/IOAudioMonitor.swift
- Sources/Media/IOAudioResampler.swift
- Sources/Media/IOAudioRingBuffer.swift
- Sources/Media/IOAudioUnit.swift
- Sources/Media/IOMixer.swift
- Sources/Media/IOMuxer.swift
- Sources/Media/IORecorder.swift
- Sources/Media/IOUnit.swift
- Sources/Media/IOVideoMixer.swift
- Sources/Media/IOVideoUnit.swift
- Sources/Net/NetStream.swift
- Sources/RTMP/RTMPMessage.swift
- Sources/RTMP/RTMPMuxer.swift
- Sources/RTMP/RTMPStream.swift
- Tests/Codec/AudioCodecTests.swift
- Tests/MPEG/TSReaderTests.swift
- Tests/Media/IOAudioResamplerTests.swift
- Tests/Media/IOAudioRingBufferTests.swift
- Tests/Media/IORecorderTests.swift
- I have reviewed the design of IOMixer. I made classes that don't need to be public private. I also renamed the method names to follow Swift's guidelines.
> Refactoring of IOMixer.

- Sources/Media/IOVideoUnit.swift
- Backporting 1.6.x. https://github.com/shogo4405/HaishinKit.swift/pull/1328 
> Backporting Fix Crashs since Xcode 14.3 compilation CIContext#render

- Sources/Media/IOVideoCaptureUnit.swift
- In order to improve performance, I have made it possible for library users to define the color format.
-  https://developer.apple.com/documentation/technotes/tn3121-selecting-a-pixel-format-for-an-avcapturevideodataoutput
> IOVideoCaptureUnit#colorFormat property

- Examples/iOS/IngestViewController.swift
- HaishinKit.xcodeproj/project.pbxproj
- Sources/Media/IOAudioCaptureUnit.swift
- Sources/Media/IOAudioUnit.swift
- Sources/Media/IOCaptureSession.swift
- Sources/Media/IOCaptureUnit.swift
- Sources/Media/IOCaptureVideoPreview.swift
- Sources/Media/IOMixer.swift
- Sources/Media/IOVideoCaptureUnit.swift
- Sources/Media/IOVideoUnit.swift
- Sources/Media/MTHKView.swift
- Sources/Media/PiPHKView.swift
- Sources/Net/NetStream.swift
- With the introduction of the ability to use an external camera in iPadOS 17, we have carried out a refactoring of the internal processes.
- Support to postpone multi camera attachment.
> Refactor IOVideoUnit#attachCamera method.

- Sources/RTMP/RTMPMessage.swift
- Sources/RTMP/RTMPStream.swift
- I implemented handling for onMetaData during RTMP playback.
> Handling RTMPDataMessage.

- Sources/IO/IOVideoUnit.swift
- Sources/Net/NetStream.swift
Since I couldn't come up with a satisfactory solution, I reverted to the 1.6.x version era.
- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1342
- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1348
> stream#videoCapture performance improvement.

- Sources/Net/NetSocket.swift
- Sources/RTMP/RTMPConnection.swift
- Sources/RTMP/RTMPMessage.swift
- Sources/RTMP/RTMPSharedObject.swift
- Sources/RTMP/RTMPStream.swift
I have fixed the issue where the value of connection.timeout could not be set as expected in the instance's state.
```
let conneciton = RTMPConnection()
conneciton.timeout = 5
```
> Fix crash set RTMPConneciton.timeout.

- Examples/iOSSwiftUI/Model/ViewModel.swift
- Examples/iOSSwiftUI/iOSSwiftUIApp.swift
- Sources/Codec/VideoCodecSettings.swift
Fixed a bug in the initial setting of video in SwiftUI example. Also changed the AVAudioSession mode to get audio working in SwiftUI example.
> Fix: SwiftUI fixes for initial video and audio

- Examples/iOS/NetStreamSwitcher.swift
- Sources/IO/IOStream.swift
This small change makes readyState open. It helps to observe changes of `readyState` property of `IOStream`.
> Change RTMPStream readyState observers to open

- Sources/IO/IOVideoMixer.swift
- Sources/IO/IOVideoMixerSettings.swift
This PR brings an option to display camera output on a drawable before applying the video effects. It allows to show the video effects only on the stream. Default value is the same as before. `effectsBuffer` flags helps to prevent the race condition when the video effects appear on the drawable for some frames; it happens when effects rendering is faster than drawable rendering.
> Add an option to show video output on a drawable without video effects

- Sources/IO/IOAudioResampler.swift
Feature: Add audio channel map validation
Here's a case I'm trying to solve:
1. User connects an audio device with 2 input channels
2. User sets the output channel map to [0, 1]
3. User disconnects the input device, so now input has only 1 channel from the default mic
4. Audio converter crashes [here](https://github.com/shogo4405/HaishinKit.swift/blob/c712fe74d7fd555ada5b533dcdbfc939f4381caf/Sources/IO/IOAudioResampler.swift#L187) because it tries to map the second channel that isn't available anymore
There are other situations like this, for instance, just setting `stream.audioSettings.channelMap = [3]`.
The problem here is that audio input and output formats are not exposed outside of the library and `channelMap` cannot be corrected before it's applied to the converter. 
Theoretically, …
> Validate audio channel map before applying

- Sources/IO/IOVideoUnit.swift
This PR fixes an issue where `inputFormat` of `IOVideoUnit` is nil. As result, `videoInputFormat` is nil when `RTMPStream` calls `makeMetaData` during camera streaming. It was working [previously](https://github.com/shogo4405/HaishinKit.swift/commit/0baa40b#diff-009d825f8c7bbcf073d4e25661a7aef9a8a87361d66a2d4e118798be8c334b74R560) when `IOVideoUnit` was calling a local "append" method that was updating `inputFormat`. Now it only passes new buffers from `IOVideoMixerDelegate` to drawable and mixer, so this PR sets the format in the delegate method too. 
> Set IOVideoUnit inputFormat when new buffer is available

- Examples/iOS/NetStreamSwitcher.swift
- Sources/RTMP/RTMPConnection.swift
- Sources/RTMP/RTMPStream.swift
- refs https://github.com/shogo4405/HaishinKit.swift/pull/1391
- I've added support for FMLE-compatible sequences. It seems that previously, we were not calling releaseStream and had the wrong order for FCPublish.
- These are not part of the RTMP specification and are provided as RCP features of FMS. It's unclear whether server-side implementations in modern times also have business logic implemented as stubs for these functionalities.
I anticipate usage like this: Please set stream.fcPublishName before calling RTMPConnection.connect.
```
stream = RTMPStream(connection, “ingest-stream-name”)
stream.fcPublishName = “ingest-stream-name”
stream.publish(stream.fcPublishName)
```
> Support FMLE-compatible sequences(releaseStream/FCPublish)

- Examples/visionOS/ContentView.swift
- Sources/Extension/AVCaptureDevice+Extension.swift
- Sources/Extension/AVCaptureDevice.Format+Extension.swift
- Sources/Extension/AVCaptureSession+Extension.swift
- Sources/Extension/AVFrameRateRange+Extension.swift
- Sources/IO/IOCaptureSession.swift
- Sources/IO/IOCaptureUnit.swift
- Sources/IO/IOMixer.swift
- Sources/IO/IOStream.swift
- Sources/IO/IOVideoCaptureUnit.swift
- Sources/IO/IOVideoUnit.swift
I have implemented support for AVCaptureSession on visionOS, as it is available. However, unfortunately, APIs such as https://developer.apple.com/documentation/avfoundation/avcaptureaudiodataoutput/ are not available on visionOS, so the attachAudio functionality could not be opened.
> Support attachVideo() for visionOS.

- Examples/iOS/Screencast/SampleHandler.swift
- HaishinKit.xcodeproj/project.pbxproj
- Sources/Codec/AudioCodecSettings.swift
- Sources/Extension/AudioNode+Extension.swift
- Sources/Extension/AudioStreamBasicDescription+Extension.swift
- Sources/IO/AudioNode.swift
- Sources/IO/IOAudioMixer.swift
- Sources/IO/IOAudioResampler.swift
- Sources/IO/IOAudioUnit.swift
- Sources/IO/IOStream.swift
- Sources/RTMP/RTMPMuxer.swift
This is a PR based on #1380. It replaces audio resampler with an audio mixer. Everything works as before when there is just one input source. Once there is more, audio mixer creates an audio graph; adds a resampler for each input source; starts the mixing process. It is using plain AudioUnit components instead of `AVAudioNode` to avoid interacting with audio session and instead of `AUAudioUnit` to avoid deprecated `AUGraph`. 
Users can provide dedicated audio settings for every input source with `sourceSettings`. This allows to set `channelMap` and other parameters independently for every resampler. However, output `sampleRate` and `channels` are enforced by the IOMixer to be the same as for the default resampler. This ensures that mixer node works with the same audio format from every …
> Add multichannel audio mixer

- Examples/macOS/SCStreamPublishViewController.swift
- Sources/IO/IOStream.swift
- Decided to remove extensions related to SCStreamOutput as we deemed them unnecessary at the framework layer.
> Remove default IOStream: SCStreamOutput extension.

- HaishinKit.xcodeproj/project.pbxproj
- Package.resolved
- README.md
- Sources/IO/IOMixer.swift
- Sources/IO/IOStream.swift
- Sources/IO/IOStreamObserver.swift
- Sources/IO/IOStreamRecorder.swift
- Sources/IO/IOVideoUnit.swift
- Tests/IO/IOStreamRecorderTests.swift
- Tests/ISO/HEVCDecoderConfigurationRecordTests.swift
- I have redesigned the sample reception of Stream to be able to receive samples from multiple objects.
- Recorder has also been modified to support multiple recorders for one stream.
> Add IOStreamObserver and confirmed IOStreamRecorder.

- Sources/Codec/AudioCodecSettings.swift
- Sources/IO/IOAudioResampler.swift
Public interface typo fix
Code Cleanup 
It is public interface variable name change. (`mamimumSampleRate` -> `maximumSampleRate`)
> Fixed typo and removed duplicated audio format flag

- Sources/ISO/TSWriter.swift
* Fix: initialization of PSI (PMT) in TSWriter for a SRTStream
When a SRT stream start, application must send PSI.
In your implementation, HaishinKit TSWriter must wait to receive both audio and video configuration (when both are required) before sending the PSI.
Unfortunately that part has a bug and PSI are sent right away (without waiting for the video configuration)
- [ x ] Bug fix (non-breaking change which fixes an issue)
> fix initialization of PSI in TSWriter

- Sources/RTMP/RTMPConnection.swift
- Sources/RTMP/RTMPMessage.swift
- Sources/RTMP/RTMPStream.swift
- Refs https://github.com/shogo4405/HaishinKit.swift/pull/1393
- I fixed an issue where unintended sequences were encountered with nginx + rtmp-module.
> Improving compatibility with FMLE's FCPublish behavior.

- Examples/iOS/Screencast/SampleHandler.swift
- HaishinKit.xcodeproj/project.pbxproj
- Sources/IO/IOAudioMixerConvertible.swift
- Sources/IO/IOAudioMixerConvertibleByMultiTrack.swift
- Sources/IO/IOAudioMixerConvertibleBySingleTrack.swift
- Sources/IO/IOAudioUnit.swift
- Sources/Util/FeatureUtil.swift
- https://github.com/shogo4405/HaishinKit.swift/pull/1386 
- I have enabled the ability to toggle the multi-track audio mixing feature on/off. This is a precautionary measure as unexpected issues may be discovered in the initial release. Please enable the feature using `FeatureUtil.setEnabled(feature: .multiTrackMixing, isEnabled: true)` and provide feedback.
> Add an ON/OFF switch for the multi-track audio mixing feature.

- Examples/iOS/IngestViewController.swift
- Examples/iOS/Screencast/SampleHandler.swift
- Examples/iOSSwiftUI/Model/ViewModel.swift
- Examples/macOS/AppDelegate.swift
- Examples/macOS/CameraIngestViewController.swift
- README.md
- Sources/IO/IOAudioCaptureUnit.swift
- Sources/IO/IOAudioUnit.swift
- Sources/IO/IOCaptureSession.swift
- Sources/IO/IOCaptureUnit.swift
- Sources/IO/IOStream.swift
- Sources/IO/IOVideoCaptureUnit.swift
- Sources/Util/FeatureUtil.swift
- I have added functionality to capture multiple streams of microphone audio on macOS.
- This allows for mixing down audio for distribution when used in conjunction with https://github.com/shogo4405/HaishinKit.swift/pull/1386.
> Added multi-capture functionality as microphone.

- Sources/Codec/AudioCodecSettings.swift
- Sources/IO/IOStreamRecorder.swift
- Sources/ISO/AudioSpecificConfig.swift
- Sources/RTMP/RTMPMuxer.swift
- The AudioCodec class now supports encoding and decoding for 3 channels to 8 channels.
1. [x] 2.1
2. [ ] 4.0
3. [x] 4.1
4. [ ] 5.1 //  [19, 176, 86, 229, 160] 5 bytes of data and couldn't parse it.
5. [ ] 7.1
1. [ ] ~2.1~
2. [x] 4.0
3. [x] 4.1
4. [x] 5.1
5. [x] 7.1
> Supports AAC codec multi-channels.

- Sources/RTMP/RTMPConnection.swift
- Support NetConnection connect Command(fourCcList)
> Extending NetConnection connect Command(fourCcList)

- Sources/IO/IOAudioMixerByMultiTrack.swift
- Sources/IO/IOAudioMixerBySingleTrack.swift
- Sources/IO/IOAudioUnit.swift
- Sources/IO/IOVideoMixer.swift
- I fixed it because the following delegate wasn't working.
- func stream(_ stream: IOStream, track: UInt8, didInput buffer: AVAudioBuffer, when: AVAudioTime)
- func stream(_ stream: IOStream, track: UInt8, didInput buffer: CMSampleBuffer)
> Fix don't call delegate methods incoming buffers.

- Examples/iOS/Preference.swift
- Examples/macOS/FLVAnalyzerViewController.swift
- Sources/RTMP/AMF0Serializer.swift
- Sources/RTMP/AMFFoundation.swift
- Sources/RTMP/RTMPStream.swift
- Tests/RTMP/AMF0SerializerTests.swift
Until now, I have been sending using ECMAObject, but according to the specifications, ECMAArray is correct. I have been mistaken since the release of HaishinKit, but I have made this change to follow Enhanced RTMP.
- https://github.com/veovera/enhanced-rtmp/blob/main/docs/enhanced/enhanced-rtmp-v2.md
> To signal FLV metadata, the item within the ScriptTagBody MUST encapsulate the method name onMetaData, along with a single argument of type ECMA array. 
> onMetaData must be ECMAArray.

- Sources/Extension/CVPixelBuffer+Extension.swift
- Sources/IO/IOVideoCaptureUnit.swift
- Sources/IO/IOVideoMixer.swift
- Sources/IO/IOVideoUnit.swift
- On macOS Sonoma 14.1 with an M1 Mac, isVideoMirrored was not working and did not mirror as intended, so it has been removed.
> Since isVideoMirrored is now working on macOS, discontinue the workaround.

- Sources/IO/IOAudioMixerSettings.swift
- Tests/IO/IOAudioMixerBySingleTrackTests.swift
- I have enabled support for more than 2 channels on our end, but since some services may not support this, I have changed the default to handle up to 2 channels. https://github.com/shogo4405/HaishinKit.swift/pull/1432
> Add maximumNumberOfChannels property.

- Examples/iOS/Screencast/SampleHandler.swift
- HaishinKit.xcodeproj/project.pbxproj
- Sources/Extension/CVPixelBuffer+Extension.swift
- Sources/Extension/VTRotationSessionOption+Extension.swift
- Sources/Screen/VideoRotator.swift
This PR adds a feature to rotate pixel buffers that come from ReplayKit. This allows to rotate video when device changes orientation. It is much more efficient than using `VideoEffect`. 
Rotation has two modes besides default `.disabled`.
```Swift
rtmpStream.videoMixerSettings.propogateReplayKitOrientation = true
rtmpStream.videoSettings.rotationMode = .automatic
```
In this case `VideoCodec` automatically determines the required rotation based on the buffer orientation.
```Swift
rtmpStream.videoSettings.rotationMode = ._90
```
This allows HK users to specify rotation manually.
* I decided to store rotation information in the `CVImageBuffer` so there is no need to modify `VideoCodec` method signatures. As result, `IOVideoMixer` saves the orientation info as an attachment of the pixel …
> Implement orientation change handling for ReplayKit

- Sources/IO/IOAudioMixerByMultiTrack.swift
When `settings` are applied to `IOAudioMixerByMultiTrack` before it receives an audio buffer, `mixerNode` is not initialized. This fix applies the volume during the node creation. Second issue is related to using non-sequential track numbers. For example, 0 for microphone, 2 for screensharing app audio. This results to only tracks 0, 1 being enabled and 2 being disabled.
> Change how track volume is applied

- Sources/IO/IOAudioMixerByMultiTrack.swift
This PR removes `shouldMix` so it would be possible to control volume even when there's only one track.
> Remove shouldMix from multitrack mixer

- Sources/RTMP/RTMPMuxer.swift
When audio or video format is changed in the middle of the stream, the muxer sends RTMP message with zero chunk type. This breaks streams on different platforms, including Twitch. RTMPStream used to have flags `audioWasSent`, `videoWasSent` to handle this case before this 65cbf34465d69c1e733af5d9a5b81a5c2adb0ad1 change. This PR doesn't bring the flags back, instead it just checks if the format was nil.
> Allow mid stream audio video format change 

- Examples/iOS/Screencast/SampleHandler.swift
This PR fixes initialization of the buffer rotator in Screencast example.
> Fix buffer rotation creation in Screencast example 

- Sources/IO/IOAudioMixerByMultiTrack.swift
This PR fixes an issue where audio tracks from multitrack mixer don't preserve their delegates. This leads to a state where AudioCodec doesn't receive current audio format from the mixer.
> Update audio track delegate on output format change

- Sources/IO/IOStream.swift
- https://github.com/shogo4405/HaishinKit.swift/discussions/1503
> Thread safety audioMixerSettings.

- Sources/Screen/Screen.swift
- Sources/Screen/ScreenObject.swift
- Sources/Screen/ScreenRenderer.swift
- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1505
- Fixed a bug where the application crashes when the ImageScreenObject is larger than the screen size or exceeds the boundaries.
> Fixed a bug where the application crashes when the area is large.

- Examples/iOS/Preference.swift
- Sources/RTMP/RTMPStream.swift
When using FMLE-compatible mode, we have changed to use deleteStream instead of closeStream.
- refs https://github.com/shogo4405/HaishinKit.swift/pull/1517
- fixed https://github.com/shogo4405/HaishinKit.swift/discussions/1511
**Expected**
> implementation deleteStream.

- README.md
- Update the documentation about SRTHaishinKit supports only iOS and tvOS for CocoaPods.
```
platform :ios, "13.0"
target 'Test' do
pod 'SRTHaishinKit', '~> 1.9.2'
end
```
> Update README.md SRTHaishinKit with CocoaPods

- HaishinKit.xcodeproj/project.pbxproj
- Sources/Screen/ChromaKeyProcessor.swift
- Sources/Screen/Screen.swift
- Sources/Screen/ScreenObject.swift
- Sources/Screen/ScreenRenderer.swift
- Sources/Screen/Shape.swift
- Sources/Screen/ShapeFactory.swift
- Added a chroma key compositing feature to live footage and archives.
```swift
let videoScreenObject = VideoTrackScreenObject()
// It cannot be used together with cornerRadius, leave it unspecified.
// videoScreenObject.cornerRadius = 32.0
videoScreenObject.track = 1
// Specify the color you want to use for chroma key compositing. This value should be the RGB representation of the fabric color.
videoScreenObject.chromaKeyColor = UIColor(red: 60 / 255, green: 204 / 255, blue: 112 / 255, alpha: 1).cgColor
videoScreenObject.horizontalAlignment = .right
videoScreenObject.layoutMargin = .init(top: 16, left: 0, bottom: 0, right: 16)
videoScreenObject.size = .init(width: 160 * 2, height: 90 * 2)
// _ = videoScreenObject.registerVideoEffect(MonochromeEffect())
```
|ON|OFF|
|:-:|:-:|
> ChromaKey filter feature.

- Sources/IO/IOCaptureSession.swift
- Sources/IO/IOMixer.swift
- Sources/IO/IOStream.swift
This PR is a fix for #1522 to make AVCaptureSession `startRunning` and `beginConfiguration` calls thread safe.
> Make AVCaptureSession calls thread safe

- Sources/IO/IOStream.swift
I added an API since there might be cases where you want to manually start the capture depending on the use case.
- https://github.com/shogo4405/HaishinKit.swift/pull/1535, https://github.com/shogo4405/HaishinKit.swift/discussions/1530
> Add (start|stop)Capturing() api.

- Cartfile
- Cartfile.resolved
- HaishinKit.xcodeproj/project.pbxproj
- HaishinKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- README.md
- Sources/ISO/TSReader.swift
- fastlane/Fastfile
- Due to the decline in Carthage usage and the inability to build with Xcode 16 beta, support for it will be discontinued with the 2.0.0 release.
- https://github.com/shogo4405/HaishinKit.swift/discussions/1488
- https://github.com/shogo4405/HaishinKit.swift/issues/1542
> Discontinued support Carthage.

- Sources/View/MTHKView.swift
- Implementation that supports video effects for MTHKView.
- https://github.com/shogo4405/HaishinKit.swift/pull/1535
> implementation that supports video effects for MTHKView.

- HaishinKit.xcodeproj/project.pbxproj
- Sources/IO/IOStream.swift
- Sources/Screen/StreamScreenObject.swift
- I added this feature because it’s useful to reflect live streaming data from another source on the screen.
> Add StreamScreenObject.

- Sources/IO/IOVideoCaptureUnit.swift
- Since the passthrough and offscreen methods now support kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange, we will change the default color format to this.
> Change the default color to kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange.

- README.md
- SRTHaishinKit/SRTConnection.swift
- SRTHaishinKit/SRTSocket.swift
- Sources/IO/IOStream.swift
- Sources/RTMP/RTMPStream.swift
- Supported SRT Listener mode.
- Only one connection is supported. By configuring as follows, you can wait as a listener to receive and play a stream from another client.
```swift
connection = SRTConnection()
stream = SRTStream(connection: connection)
stream.play()
view.attachStream(stream)
connection.open(URL(string: "srt://0.0.0.0:9998"), mode: .listener)
```
> Support SRT listener mode.

- Sources/IO/IOStreamRecorder.swift
- It possible to specify the movieFragmentInterval to recover from crashes or unintended task termination.
> Add the movieFragmentInterval value to the recording feature.

- Sources/Screen/ScreenObject.swift
- Sources/Screen/ScreenRenderer.swift
- Sources/Screen/StreamScreenObject.swift
- I have optimized the CPU usage.
- I've set it to use vImageCopy when alpha rendering is not needed, to avoid unnecessary computations.
**Before**
`iPhone 16 Pro max: 40-50%`
**After**
`iPhone 16 Pro max: 35-45%`
> Optimize ScreenObject CPU usage.

- Sources/Extension/CVPixelBuffer+Extension.swift
- Sources/IO/MTHKView.swift
- I optimized the rendering of MTHKView. In the WWDC session, context.startTask was recommended for rendering, so I replaced it accordingly.
- https://developer.apple.com/videos/play/wwdc2020/10008
**Before**
`iPhone 16 Pro max: 35-45%`
**After**
`iPhone 16 Pro max: 30-35%`
- There is some fluctuation every time it's transferred to the actual device, but since it's stabilizing around 30-35
> Optimize MTHKView.swift

- Sources/HKStream/HKStreamRecorder.swift
in `startRecording ` it fileName was miss typed to filaName and settings parameter was unused.
> Fix: recording filename typo, settings parameter set correctly

- Sources/Extension/AVCaptureSession+Extension.swift
- Sources/Mixer/AudioMixerByMultiTrack.swift
- Sources/Mixer/AudioMonitor.swift
- Sources/Mixer/AudioRingBuffer.swift
- Sources/RTMP/RTMPStream.swift
- Sources/Screen/Shape.swift
AVCaptureSession extension was redeclared if targetEnvironment(macCatalyst) was used
Modified AVCaptureSession extension to separate  targetEnvironment(macCatalyst) and rest of the extension
- [ x] Bug fix (non-breaking change which fixes an issue)
> Fix: build issue where mac catalyst target had AVCaptureSession extension redeclaration

- Examples/iOS/Screencast/SampleHandler.swift
- HaishinKit.xcodeproj/project.pbxproj
- Sources/HKStream/HKStreamRecorder.swift
- Tests/HKStream/HKStreamRecorderTests.swift
- Added validation when a file is specified at the start of recording. An exception will be thrown if the file already exists.
- https://github.com/shogo4405/HaishinKit.swift/pull/1611
> Added validation at the start of recording.

- HaishinKit/Sources/HKStream/MediaLink.swift
- HaishinKit/Sources/Screen/DisplayLinkChoreographer.swift
- fixed an issue with the handling of CADisplayLink's duration.
> fixed an issue with the handling of CADisplayLink's duration.

- HaishinKit.xcodeproj/xcshareddata/xcschemes/Example iOS.xcscheme
- Sources/IO/MediaLink.swift
- Sources/Screen/Choreographer.swift
- Sources/Screen/Screen.swift
- https://github.com/shogo4405/HaishinKit.swift/pull/1624
- Fixed an issue where the screen FPS could not be changed midway.
> backport #1624 to 1.9.x

- HaishinKit.xcodeproj/project.pbxproj
- Sources/IO/IOVideoMixer.swift
- Sources/IO/IOVideoUnit.swift
- Sources/Screen/Screen.swift
- Sources/Screen/ScreenObject.swift
- Sources/Screen/ScreenRenderer.swift
- Sources/Util/FrameTracker.swift
- Sources/Util/TypedBlockQueue.swift
- Fixed an issue where unintended frame drops occurred when using the offscreen rendering feature.
> Take timestamps into consideration VideoTrackScreenObject.

- Examples/iOS/IngestViewController.swift
- HaishinKit/Sources/Mixer/MediaMixer.swift
- Added an option to manually start capturing camera and microphone data.
- This behavior is planned to be the default in the 2.1.x series.
- The main background for this implementation is explained here: 
- https://github.com/shogo4405/HaishinKit.swift/discussions/1637
```swift
let mixer = MediaMixer(
multiCamSessionEnabled: true, 
multiTrackAudioMixingEnabled: false,
// Please set to true. default value is false.
useManualCapture: true
)
mixer.attachAudio()
mixer.attachVideo()
// Must call startRunning()
mixer.startRunning()
```
> Add an option to start capture manually.

- HaishinKit/Sources/Mixer/AudioCaptureUnit.swift
- HaishinKit/Sources/Mixer/MediaMixer.swift
- HaishinKit/Sources/Mixer/VideoCaptureUnit.swift
- HaishinKit/Sources/Screen/DisplayLinkChoreographer.swift
- fixed https://github.com/shogo4405/HaishinKit.swift/issues/1651
> fix memory-leak a MediaMixer instance.

- HaishinKit/Sources/Mixer/CaptureSession.swift
- HaishinKit/Sources/Mixer/MediaMixer.swift
- I have migrated the processing of CaptureSessionDelegate from the 1.9.x series to 2.0.x.
> Migration CaptureSessionDelegate to 2.0.x.

- HaishinKit/Sources/Codec/AudioCodec.swift
- HaishinKit/Sources/Codec/VideoCodec.swift
- HaishinKit/Sources/HKStream/HKOutgoingStream.swift
- HaishinKit/Sources/Network/NetworkMonitor.swift
- HaishinKit/Sources/RTMP/RTMPStream.swift
- refs https://github.com/shogo4405/HaishinKit.swift/issues/1651
- I fixed the issue as there were leaks not only in MediaMixer but elsewhere as well.
- RTMPConnection
- RTMPStream
> fix memory-leak RTMPConnection, RTMPStream.

- HaishinKit/Sources/Codec/AudioCodec.swift
- HaishinKit/Sources/Codec/AudioCodecSettings.swift
- HaishinKit/Sources/Codec/OpusHeaderPacket.swift
- HaishinKit/Sources/RTMP/RTMPConnection.swift
- HaishinKit/Sources/RTMP/RTMPEnhanced.swift
- HaishinKit/Sources/RTMP/RTMPFoundation.swift
- HaishinKit/Sources/RTMP/RTMPMessage.swift
- HaishinKit/Tests/RTMP/RTMPVideoFourCCTests.swift
Support for the OPUS extension in Enhanced RTMP.  This PR is for Ingest only. I’d like to implement Playback as well, but I can’t find a product with server-side support. Could someone help?
```swift
var audioSettings = AudioCodecSettings()
audioSettings.format = .opus
await stream.setAudioSettings(audioSettings)
```
- I tests using mediamtx.
- Ingest H264 + Opus
- There seems to be some audio dropouts, but it's unclear whether the issue lies with HaishinKit or some other factor.
```
ffplay http://localhost:8888/live/live/index.m3u8
```
> Ingest Support the OPUS format for Enhanced RTMP.

- HaishinKit/Sources/Codec/AudioCodec.swift
- HaishinKit/Sources/Codec/AudioCodecSettings.swift
- HaishinKit/Sources/Mixer/AudioRingBuffer.swift
- HaishinKit/Sources/RTMP/RTMPEnhanced.swift
- HaishinKit/Sources/RTMP/RTMPStream.swift
- HaishinKit/Tests/Codec/AudioCodecSettingsFormatTests.swift
OPUS support has been added here.
- https://github.com/shogo4405/HaishinKit.swift/pull/1674
Since OPUS has fixed supported sample rates, it is more convenient to allow changing the sampling rate per stream, so this modification was made.
> allow changing the sampleRate for each stream.

- HaishinKit/Sources/ISO/PacketizedElementaryStream.swift
fixed an issue where packets could be dropped when the PES size was large.
- refs https://github.com/shogo4405/HaishinKit.swift/issues/1677
> fixed Large PES packets could be dropped.

- HaishinKit/Sources/RTMP/RTMPChunk.swift
- HaishinKit/Tests/RTMP/RTMPChunkBufferTests.swift
- fixed an issue where resetting the RTMP ChunkSize would cause a crash.
1. Call rtmpStream#play.
2. Stop
3. Call rtmpStream#play.
> Fix crash resetting the RTMP ChunkSize.

- SRTHaishinKit/Sources/SRT/SRTConnection.swift
- SRTHaishinKit/Sources/SRT/SRTSocket.swift
- Update and correction of SRT statistical information, etc.
> Update and correction of SRT statistical information, etc.

- SRTHaishinKit/Sources/SRT/SRTLogger.swift
- SRTHaishinKit/Sources/SRT/SRTSocket.swift
Fixed an issue where the logging API could not be configured in the 2.0.x series.
```swift
await SRTLogger.shared.setLevel(.notice)
```
> The logging level could not be set.

- SRTHaishinKit/Sources/SRT/SRTConnection.swift
- SRTHaishinKit/Sources/SRT/SRTStream.swift
- SRTHaishinKit/Tests/SRT/SRTConnectionTests.swift
- The behavior of the SRT listener has also become a blocking process during connection, just like the caller.
> Modified to use blocking processing while the listener is waiting.

- Examples/Examples.xcodeproj/xcuserdata/shogo.endo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
- SRTHaishinKit/Sources/SRT/SRTConnection.swift
- SRTHaishinKit/Sources/SRT/SRTLogger.swift
- SRTHaishinKit/Sources/SRT/SRTSocket.swift
- SRTHaishinKit/Sources/SRT/SRTSocketOption.Name.swift
- SRTHaishinKit/Sources/SRT/SRTSocketOption.swift
- SRTHaishinKit/Tests/SRT/SRTConnectionTests.swift
- SRTHaishinKit/Tests/SRT/SRTSocketOptionTests.swift
- API to set SRT socket options externally.
> New SRTSocketOption api.

- Examples/iOS/IngestViewController.swift
- HaishinKit/Sources/Mixer/AudioNode.swift
First of all, Thank you so much about you and your frameworks.
I'm using multi channel mixer mode from 1.8.x
It works well until Xcode 16.2, but it occurs runtime error with Xcode 16.3
(Seems MixerNode and OutputNode released so fast than expected - I assumed some kind of Swift runtime bug so I posted to [swift.org forums](https://forums.swift.org/t/different-instance-life-cycle-with-inout-between-xcode16-2-and-16-3/79631) )
To occur, just change multiTrackAudioMixingEnabled flags to true at 27th line in IngestViewController with Xcode 16.3
I fixed MixerNode description values as local value for inout arguments, to avoid runtime BAD_ACCESS_ERROR.
- Bug fix (non-breaking change which fixes an issue)
I hope it will be helpful.
> Fixed for multi channel mixer works well with Xcode16.3
